### ISSUE TITLE
regex replace html in file

### ISSUE THREAD

**Issue by amlwwalker** [elazarl/goproxy#103]
Is there a nice function within goproxy to replace/insert html into the html response? 

Maybe regex look for something and replace it with something else - like replace an image with another image or something?

**Comment by elazarl** [comment]
What I would do, is parse the HTML body with Go HTML parser, and then traverse the tree replacing whatever I wish.

**Comment by amlwwalker** [comment]
Something like:

```
	proxy.OnResponse().DoFunc(func(resp *http.Response, ctx *goproxy.ProxyCtx) *http.Response {
			d := html.NewTokenizer(resp.Body)
			for {
					tokenType := d.Next()
					if tokenType == html.ErrorToken {
						return resp
					}
					switch tokenType {
					case html.ErrorToken:
						return resp
					case html.StartTagToken:
						//missing self closing token
					case html.TextToken:
					case html.EndTagToken:
					token := d.Token()
					if token.String() == "body" {
						//replace the token String with the injected html
					}
				}
				log.Println("still in here")
			}
		return resp
	})
```

results in 'still in here' being printed forever

**Comment by elazarl** [comment]
It looks like you have an infinite loop.

I suggest you'll try to parse a simple HTML file without using proxy at
all, say, in Go playground, and then when you got that working put it in
the proxy.
