### ISSUE TITLE
Stopping the proxy

### ISSUE THREAD

**Issue by amlwwalker** [elazarl/goproxy#104]
I have the proxy running in a `go routine` but I want to change the parameters every so often of the proxy, without quitting the program. What is the best way to do that?
I am using the revel framework, so the Index() (instead of main) continues to run, stopping main quitting
```
func stopProxy() {
	//what here?
}

func handleProxyOnRoutine() {
	verbose := flag.Bool("v", false, "should every proxy request be logged to stdout")
	addr := flag.String("addr", ":8080", "proxy listen address")
	flag.Parse()
	proxy := goproxy.NewProxyHttpServer()
	proxy.Verbose = *verbose
	log.Fatal(http.ListenAndServe(*addr, proxy))
}

func (c App) Index() revel.Result {
	go handleProxyOnRoutine()
	return c.Render()
}
```
I realise that this is a combination of routine/channels and stopping the proxy properly, but its not clear to me about how I would do this.

**Comment by elazarl** [comment]
close the listener of the gorproxy and start it again.

func run(l net.Listener) {
    http.Server(l, proxy)
}
// from other thread
l.close()
l, _ := net.Listen(*addr)
run(l)

**Comment by amlwwalker** [comment]
So I dont think I understand it exactly.... `l.close()` doesnt exist against a listener:

```
func handleProxyOnThread(l net.Listener) {

    verbose := flag.Bool("v", false, "should every proxy request be logged to stdout")
    addr := flag.String("addr", ":8080", "proxy listen address")
    flag.Parse()
    proxy := goproxy.NewProxyHttpServer()
    proxy.Verbose = *verbose
	log.Fatal(http.ListenAndServe(l.Addr().String(), proxy))
}

func (c App) Index() revel.Result {


	laddr, err := net.ResolveTCPAddr("tcp", "127.0.0.1:8090")
	if nil != err {
		log.Fatalln(err)
	}
	listener, err := net.ListenTCP("tcp", laddr)
	if nil != err {
		log.Fatalln(err)
	}
	log.Println("listening on", listener.Addr())

	go handleProxyOnThread(listener)
	return c.Render()
}
```

Have I missed the point?

**Comment by elazarl** [comment]
Don't use http.ListenAndServe

Create the listener with net.Listen, and then serve by http.Serve. When you
have the listener, close it from other goroutine and serving would stop.

**Comment by amlwwalker** [comment]
Ok so close now!
When I close the listener however, and then start it back up again, I get a strange error - remember I am using this inside the Revel web framework:

```
const (
    CONN_HOST = "localhost"
    CONN_PORT = "8080"
    CONN_TYPE = "tcp"
)
var listener net.Listener

func handleProxyOnThread() {

    verbose := flag.Bool("v", false, "should every proxy request be logged to stdout")
    flag.Parse()
    proxy := goproxy.NewProxyHttpServer()
    proxy.Verbose = *verbose
	log.Fatal(http.Serve(listener, proxy))
}

func (c App) KillProxy() revel.Result {
	listener.Close()
	return c.RenderJson("")
}

func (c App) Index() revel.Result {
    listener, _ = net.Listen(CONN_TYPE, CONN_HOST+":"+CONN_PORT)
	log.Println("listening on", listener.Addr())

	go BlockWebsites(listener)
	return c.Render()
}
```
So it stops the listener correctly, but starting it then again fails - I get the error:

```
http: proxy error: dial tcp 127.0.0.1:59768: connection refused
```
Is closing the connecting and then starting it back up again (by going to the Index endpoint) not starting it properly?

**Comment by amlwwalker** [comment]
OK so the proxy seems to work perfectly its just the closing of the routine and the listener without killing the program that I am struggling with. Based on the demo code, if I have this:

```
	listener.Close()
	listener, _ := net.Listen(CONN_TYPE, CONN_HOST+":"+CONN_PORT)
	go FlipImages(listener)
```
and I run that after
```
	listener, _ := net.Listen(CONN_TYPE, CONN_HOST+":"+CONN_PORT)
	go BlockWebsites(listener)
```
I get it erroring out because the routine isnt closed (I THINK) when the listener is - I get 


```
2015/05/20 18:07:43 ProxyControllers.go:146: accept tcp 127.0.0.1:8080: use of closed network connection
2015/05/20 18:07:43 reverseproxy.go:141: http: proxy error: EOF
```

**Comment by vogrelord** [comment]
How did you solve that error message?

**Comment by azak-azkaran** [comment]
You could just use the http.server it has a shutdown function in the latest golang version:

```
server = &http.Server{
  Addr:    "localhost:8082",
  Handler: proxy,
}
go func() {
  fmt.Println(endServer.ListenAndServe())
}()
err = endServer.Shutdown(context.Background())
```
