### ISSUE TITLE
SNI CONNECT intercept

### ISSUE THREAD

**Issue by amlwwalker** [elazarl/goproxy#105]
There is a fork of your code by abourget that implements SNI capturing. His example looks like this:

```
    proxy.HandleConnectFunc(func(ctx *goproxy.ProxyCtx) goproxy.Next {
        if ctx.SNIHost() == "google.com" {
            ctx.SetDestinationHost("www.bing.com:443")
            // so that Bing receives the right `Host:` header
            ctx.Req.Host = "www.bing.com"
        }
        return goproxy.MITM
    })
```

Does your library support something similar. I would rather be able to return responses/Requests for these situations, however I can't see in yours how to handle a CONNECT and to get the SNIHost out.

**Comment by elazarl** [comment]
Hi,

It currently doesn't handle this case.

It definitely should, and I'm thinking what's the best way to do that.

In the mean time - do use abourget's fork. We hope to merge the code bases
after a solution is found.

**Comment by amlwwalker** [comment]
I've realised I don't need to handle the SNI as that has already started the TLS handshake, and I need to cut it off before then. In abourget's fork, there is a method
```
if ctx.Method == "CONNECT" {
}
```
in otherwords I can get the Method of CONNECT. How can I handle this in the your library? The problem I am having with abourget's fork is being able to return a custom response:
```
	proxy.HandleConnectFunc(func(ctx *goproxy.ProxyCtx) ... {
		if ctx.Method == "CONNECT" {
			log.Println("Connecting: ", ctx.Req.Host)
			//return a custom response here
		}
	})
```

How do I pick up the HandleConnect in your library - the above is the abourget method, if I want to catch the connect and check the method is connect, does that exist in your version?

Alex
