### ISSUE TITLE
Can i use this to proxying (without modifying/processing) HTTPS site.

### ISSUE THREAD

**Issue by bool4ng** [elazarl/goproxy#106]
Hello,

I want to use this proxy like Squid proxy does, not to do any fancy stuff.

It works fine with HTTP site, cool!

But it not works with https site,example : https://www.google.com and https://yahoo.com

My firefox got this message:
```
The proxy server is refusing connections
```

I got this in goproxy log
```
2015/05/25 06:46:31 ServeHTTP
2015/05/25 06:46:31 [007] INFO: Got normal request / yahoo.com GET http://yahoo.com/
2015/05/25 06:46:31 [007] INFO: Sending request GET http://yahoo.com/
2015/05/25 06:46:32 [007] INFO: Received response 301 Redirect
2015/05/25 06:46:32 [007] INFO: Copying response to client 301 Redirect [301]
2015/05/25 06:46:32 [007] INFO: Copied 1450 bytes to client error=<nil>
```
First two lines are my small modification.

I use simple example in this project's main page
```
func main() {
    proxy := goproxy.NewProxyHttpServer()
    proxy.Verbose = true
    log.Fatal(http.ListenAndServe(":8080", proxy))
}
```

Any pointer to handle HTTPS?

Thanks

**Comment by bool4ng** [comment]
Sorry, i was wrong. There was no log in goproxy when user access https site.

**Comment by elazarl** [comment]
Hi,

I just tried to run

$ cd $GOPATH/src/github.com/elazarl/goproxy
$  go run ./examples/goproxy-basic/main.go -v

I accessed https://twitter.com, and received the following log:

 2015/05/25 14:46:18 [001] INFO: Got request / s2.symcb.com POST
http://s2.symcb.com/
2015/05/25 14:46:18 [001] INFO: Sending request POST http://s2.symcb.com/
2015/05/25 14:46:18 [001] INFO: Received response 200 OK
2015/05/25 14:46:18 [001] INFO: Copying response to client 200 OK [200]
2015/05/25 14:46:18 [001] INFO: Copied 1762 bytes to client error=<nil>
2015/05/25 14:46:18 [002] INFO: Got request / sr.symcd.com POST
http://sr.symcd.com/
2015/05/25 14:46:18 [002] INFO: Sending request POST http://sr.symcd.com/
2015/05/25 14:46:18 [002] INFO: Received response 200 OK
2015/05/25 14:46:18 [002] INFO: Copying response to client 200 OK [200]
2015/05/25 14:46:18 [002] INFO: Copied 1595 bytes to client error=<nil>
2015/05/25 14:46:20 [003] INFO: Got request /ocsp clients1.google.com POST
http://clients1.google.com/ocsp
2015/05/25 14:46:20 [003] INFO: Sending request POST
http://clients1.google.com/ocsp
2015/05/25 14:46:20 [003] INFO: Received response 200 OK
2015/05/25 14:46:20 [003] INFO: Copying response to client 200 OK [200]
2015/05/25 14:46:20 [003] INFO: Copied 463 bytes to client error=<nil>
2015/05/25 14:46:20 [004] INFO: Got request /ocsp clients1.google.com POST
http://clients1.google.com/ocsp
2015/05/25 14:46:20 [004] INFO: Sending request POST
http://clients1.google.com/ocsp
2015/05/25 14:46:20 [004] INFO: Received response 200 OK
2015/05/25 14:46:20 [004] INFO: Copying response to client 200 OK [200]
2015/05/25 14:46:20 [004] INFO: Copied 463 bytes to client error=<nil>
2015/05/25 14:46:41 [005] INFO: Got request
/openh264-linux64-4adf9cd6dd1358eefe3cbb5eddbfbf4ff06cfa65.zip
ciscobinary.openh264.org GET
http://ciscobinary.openh264.org/openh264-linux64-4adf9cd6dd1358eefe3cbb5eddbfbf4ff06cfa65.zip
2015/05/25 14:46:41 [005] INFO: Sending request GET
http://ciscobinary.openh264.org/openh264-linux64-4adf9cd6dd1358eefe3cbb5eddbfbf4ff06cfa65.zip
2015/05/25 14:46:41 [006] INFO: Got request / ocsp.digicert.com POST
http://ocsp.digicert.com/
2015/05/25 14:46:41 [006] INFO: Sending request POST
http://ocsp.digicert.com/
2015/05/25 14:46:41 [005] INFO: Received response 200 OK
2015/05/25 14:46:41 [005] INFO: Copying response to client 200 OK [200]
2015/05/25 14:46:41 [006] INFO: Received response 200 OK
2015/05/25 14:46:41 [006] INFO: Copying response to client 200 OK [200]
2015/05/25 14:46:41 [006] INFO: Copied 471 bytes to client error=<nil>
2015/05/25 14:46:42 [005] INFO: Copied 447140 bytes to client error=<nil>

Here is how it looked on the browser.

[image: Inline image 1]
Can you try doing the same thing and report the results?

**Comment by bool4ng** [comment]
@elazarl 
Thanks for your response.

And i am really sorry about this noise.
I forget to click "use this proxy server for all protocols" :(.

I though i have no mistake in browser config because http worked fine.

Thanks!
