### ISSUE TITLE
Support for SOCKS5 upstream proxy

### ISSUE THREAD

**Issue by j16sdiz** [elazarl/goproxy#112]
Want to use this with a SOCKS5 upstream proxy
Maybe some method to use alternative dialer ?

This have a dialer for SOCKS5: https://godoc.org/golang.org/x/net/proxy

**Comment by elazarl** [comment]
You have proxy.Tr.Dial, and proxy.ConnectDial which you can override for a
custom dialer.

**Comment by ErikPelli** [comment]
https://github.com/elazarl/goproxy/issues/558
