### ISSUE TITLE
Number of connected users

### ISSUE THREAD

**Issue by amlwwalker** [elazarl/goproxy#117]
Anyway of knowing how many users are currently connected - perhaps with mac addresses?

**Comment by elazarl** [comment]
as proxy client, or connections to external servers?

At any rate, any standard method of http's standard library.

**Comment by amlwwalker** [comment]
As proxy clients

**Comment by ErikPelli** [comment]
For the number of active connection, you can use the functions of a normal http Server, check this stackoverflow thread: https://stackoverflow.com/questions/51317122/how-to-get-number-of-idle-and-active-connections-in-go

For the MAC addresse part, they have nothing to do with the layer 3 of the ISO/OSI model, which is used for Internet communication. They are used only for the data link layer in local networks and there is no way to obtain it in an HTTP server...
