### ISSUE TITLE
Use onRequest for HTTP(s) connections

### ISSUE THREAD

**Issue by fortytw2** [elazarl/goproxy#124]
Hey! I'm trying to use onRequest to edit/return special responses in a lot of cases with `goproxy`, but it seems any request directly to an `https://` URL doesn't use this, instead does it's own thing? Anything that first goes through `http://` and is redirected works just fine though

**Comment by skytraveler** [comment]
I got the same problems

**Comment by rahulwa** [comment]
You need to do man-in-the-middle attack for https first, so that goproxy can read/intercept the traffic.
Something like this.
https://github.com/rahulwa/camouflage/blob/master/proxy/proxy.go#L116-L120

**Comment by AnoopPutta** [comment]
It still doesnt work for https when i set MITM. Any other solution please.

**Comment by ErikPelli** [comment]
You have to do MITM and also call HandleConnect(), to intercept the CONNECT request correctly
