### ISSUE TITLE
Does goproxy support reading/decoding data from chunked/gzipped http response body?

### ISSUE THREAD

**Issue by chenzx** [elazarl/goproxy#138]
I've read through the full source code, and didn't find.

Anyway, there may not be a problem. For it will do function well for a proxy server sole.

But, if I:
(1)Want to dump all body data of image/* type;
(2)& Decode the image file raw bytes

Then maybe i need considering this problem.

**Comment by elazarl** [comment]
The decoding and encoding of request is done by the net/http framework
which indeed supports chunked and gzipped request according to the client's
header.

**Comment by elazarl** [comment]
BTW, I think that posting to the mailing list of goproxy-dev is a better way to ask question than opening an issue.
