### ISSUE TITLE
Guessing host when not avilable

### ISSUE THREAD

**Issue by AlmogBaku** [elazarl/goproxy#149]
When you request an absolute URL on squid, it' detect automatically the `Host`:
```
GET http://bot.whatismyipaddress.com/ HTTP/1.1


```

However, since goproxy uses the builtin http-server, it fails to detect it and throws error:
```
400 Bad Request: missing required Host headerConnection closed by foreign host.
```
https://github.com/golang/go/blob/master/src/net/http/server.go#L718

**Comment by elazarl** [comment]
Can you please explain how to reproduce? All proxy request are exactly in the form of `GET http://url/`, so I'm not sure I understand

**Comment by elazarl** [comment]
Isn't the Host field mandatory for HTTP/1.1?

Looks like it's OK not to accept it.
Is there any use case where the client does not send the Host parameter?



9 Method Definitions

   The set of common methods for HTTP/1.1 is defined below. Although
   this set can be expanded, additional methods cannot be assumed to
   share the same semantics for separately extended clients and servers.

   The Host request-header field (section 14.23) MUST accompany all
   HTTP/1.1 requests.
