### ISSUE TITLE
Does goproxy support fanout

### ISSUE THREAD

**Issue by smileyogurt** [elazarl/goproxy#150]
I am designing a fanout project, in which the client sends a request to the leader of a cluster, then the leader distributes the request to all of its followers. When the leader receive the responses of all requests, the leader will assemble them to be the final response and send back to the client.

I am thinking to use goproxy on the lead to listen on a specific port for the incoming requests, but I am not sure if  goproxy supports the request distribution to multiple nodes?

**Comment by elazarl** [comment]
You can override the HTTP transport of the proxy to achieve it.

**Comment by rusenask** [comment]
Or you can also define your OnRequest function to do this or any other required logic

**Comment by JensRantil** [comment]
I think this issue has been answered and propose we close it.
