### ISSUE TITLE
Add a use-case list to the readme?

### ISSUE THREAD

**Issue by haoxins** [elazarl/goproxy#152]
I write a `proxy tool` for development that deps `goproxy`, see https://github.com/coderhaoxin/hp
May I ask to add a `mention` to the readme?

**Comment by ErikPelli** [comment]
I don't see anything in the specified URL. If you want to introduce your usage of goproy to us, follow the case study section in the README: https://github.com/elazarl/goproxy?tab=readme-ov-file#submit-your-case-study
