### ISSUE TITLE
Add connection add/remove events

### ISSUE THREAD

**Issue by johnmah** [elazarl/goproxy#157]
It would be nice feature (from an devops perspective) to be able to know when proxy connections are opened and closed. Currently we can use the http.Server.ConnState listener to manage normal HTTP requests, but as soon as Hijack is called we lose the ability to detect when those connections are closed (StateHijacked gets called but does not necessarily mean the connection is closed).

**Comment by elazarl** [comment]
I think the best way to do that is to override proxy.Tr http transport, and
having a custom dialer there.

See for example
https://github.com/elazarl/goproxy/blob/master/examples/goproxy-httpdump/httpdump.go#L254
