### ISSUE TITLE
Chain proxy servers

### ISSUE THREAD

**Issue by drewwells** [elazarl/goproxy#163]
How would one proxy send connections to a second proxy? One proxy lives within a VPN, so I'd like to have a front proxy that handles requests or decides to send some to a second proxy to make connections within a VPN.

**Comment by elazarl** [comment]
You should define the http.Transport inside proxy.Tr to use the second
proxy.

**Comment by drewwells** [comment]
Inside transport.Dial() the http request has been unwrapped from the original HTTP connect. Are there some conveniences to create a proper HTTP connect to the upstream proxy?

**Comment by elazarl** [comment]
Don't need dial

Something along the lines of

    proxy.Tr = &http.Transport{Proxy:func(req *http.Request) { return
myproxy }}

https://golang.org/pkg/net/http/#Transport

**Comment by drewwells** [comment]
hmm, I got it working with Dial. I'll try this approach too

```
	remoteaddr := c.Remote
	u, err := url.Parse(remoteaddr)
	if err != nil {
		log.Fatal("failed to parse upstream server:", err)
	}
	fmt.Println("upstream server", remoteaddr)

	dial := func(network, addr string) (net.Conn, error) {
		// Prevent upstream proxy from being re-directed
		if u.Host == addr {
			return net.Dial(network, addr)
		}
		fmt.Println("tr... dial", addr)
		dialer := svr.NewConnectDialToProxy(remoteaddr)
		if dialer == nil {
			panic("nil dialer, invalid uri?")
		}
		return dialer(network, addr)
	}

	svr.Tr = &http.Transport{
		Dial:    dial,
		DialTLS: dial,
	}

	log.Fatal(http.ListenAndServe(c.Listen, svr))

```

**Comment by drewwells** [comment]
tr.Proxy doesn't appear to intercept calls made via ssh

```
Host serverInsideVPN
    ProxyCommand corkscrew localhost 7800 %h %p
```

This does work with a straight ProxyServer not using a custom transport

**Comment by drewwells** [comment]
I added this dialer to catch ssh requests which seems to work well enough. Dialers receive only a host address, so it creates a URL compatible with what is expected inside proxy for a `rules(config{}, *url.URL)` 

```
	dial := func(network, addr string) (net.Conn, error) {
		u := &url.URL{Host: addr}
		// non-HTTP traffic seems to not use proxy, check again here
		// ensuring we aren't preventing access to the remote address
		if !rules(c, u) {
			return net.Dial(network, addr)
		}
		fmt.Println("dialer caught...", addr)
		return svr.NewConnectDialToProxy(remoteaddr)(network, addr)
	}
```

**Comment by drewwells** [comment]
It seems that chaining proxies causes some weird IO hanging.

**Comment by mdsalman729** [comment]
Any update on this? 
Is proxy chaining working with golang now?

**Comment by alexelisenko** [comment]
This implementation is working for me:

```
func startProxy(addr string) {
	proxy := goproxy.NewProxyHttpServer()
	
	proxy.Tr = &http.Transport{Proxy: func(req *http.Request) (*url.URL, error) {
		return url.Parse("http://<NEXT_FORWARD_PROXY_HOST>:<NEXT_FORWARD_PROXY_PORT>")
	}}
	proxy.ConnectDial = proxy.NewConnectDialToProxy("http://<NEXT_FORWARD_PROXY_HOST>:<NEXT_FORWARD_PROXY_PORT>")

	http.ListenAndServe(addr, proxy)
}
```

**Comment by elazarl** [comment]
Thanks @alexelisenko , can I close the issue?
