### ISSUE TITLE
Server-wise userdata?

### ISSUE THREAD

**Issue by dpc** [elazarl/goproxy#165]
It seems that there is a per-request userdata, but I couldn't find one for the whole server instance. It would be nice if from any request I could hop through `goproxy.Ctx` to `goproxy.Server` and that would have `userdata`.

**Comment by elazarl** [comment]
which data are you looking for?

**Comment by dpc** [comment]
`proxyCtx` does have `UserData` field. I think `ProxyHttpServer` should get one too. Then  `proxy` in `proxyCtx` should be made public so one can access `proxyCtx.Proxy.UserData`

**Comment by elazarl** [comment]
What prevents you from using a variable? Like this

userdata := foo
proxy.OnRequest(func(...) {
  foo(userdata)
}

**Comment by dpc** [comment]
The fact that I don't want globals. Eg. for testing I'm spawning multiple instances of goproxy, and they must not share the userdata.

**Comment by elazarl** [comment]
func spawn(data string) {
    proxy := goproxy.New..
    proxy.OnRequest(func(...) { foo(user1) }
    return proxy
}
spawn("one")
spawn("two")

**Comment by dpc** [comment]
That would work. I like the structure of server-wise UserData better (since I already did add UserData in my vendored copy) as it puts the ownership explicitly into server instance. Now I need to have a closure in OnRequest, but etc. But I guess the above is an OK solution too, so I'm closing the issue. Thanks!

**Comment by elazarl** [comment]
Thanks,

The problem is, adding many such small and useful features would add
weight, and make the whole API more confusing.
