### ISSUE TITLE
Logs should be in a goroutine

### ISSUE THREAD

**Issue by AlmogBaku** [elazarl/goproxy#170]
logs dramatically increase the slowness of the proxy, and they should be conducted inside a goroutine

**Comment by elazarl** [comment]
When does the log actually happen?

In normal situation it should only log when problem occurs.

That being said, we should let people set their own log function, for other
reasons. And what you suggest is a good default.

**Comment by AlmogBaku** [comment]
regarding the logging, see the discussion of me and @abourget on the slack about using the common github.com/go-kit/kit/log

**Comment by elazarl** [comment]
I'm more interested to know whether there are actual cases where logging
hinders performance today, or is it just a general concern.

**Comment by ErikPelli** [comment]
Currently logger is an interface in the proxy server and you can spawn the coroutines inside your custom implementation of the logger
