### ISSUE TITLE
The type limited is no useful

### ISSUE THREAD

**Issue by joyhope** [elazarl/goproxy#174]
latest code
        tTargetSiteCon := targetSiteCon.(_net.TCPConn)
        tProxyClient := proxyClient.(_net.TCPConn)
        go copyAndClose(ctx, tTargetSiteCon, tProxyClient)
        go copyAndClose(ctx, tProxyClient, tTargetSiteCon)

In fact, the targetSitCon, proxyClient should not be net.TCPConn, it could be any type which implement the writer, and reader interface.

The latest code cause my small application does not work.

**Comment by elazarl** [comment]
It is not clear to me how to redirect connection without being able to
readClose and writeClose

What I propose is to add an interface with writeClose and readClose you can
implement.

What do you think?

**Comment by joyhope** [comment]
>>What I propose is to add an interface with writeClose and readClose you can implement.
This is proper.  net.TCPConn is beyond the copyAndClose requirement.

**Comment by ErikPelli** [comment]
Currently we have replaced the conn with an `halfClosable` interface that does this.
Closing this issue.
