### ISSUE TITLE
 Improperly formatted DER-encoded message

### ISSUE THREAD

**Issue by Glavic** [elazarl/goproxy#182]
In Firefox v48 I get following error while connecting to HTTPS website on which I use MITM:

> An error occurred during a connection to wikipedia.org. security library: improperly formatted DER-encoded message. Error code: SEC_ERROR_BAD_DER

Script I use:

```
func main() {
    proxy := goproxy.NewProxyHttpServer()

    condition := goproxy.UrlMatches(regexp.MustCompile("^wikipedia.org:443"))

    proxy.OnRequest(condition).HandleConnect(goproxy.AlwaysMitm)
    proxy.OnResponse(condition).DoFunc(func(res *http.Response, ctx *goproxy.ProxyCtx) *http.Response {
        b, _ := ioutil.ReadAll(res.Body)
        res.Body = ioutil.NopCloser(bytes.NewBuffer(b))
        go DoStuff(b)
        return res
    })

    log.Fatal(http.ListenAndServe(":8081", proxy))
}

func DoStuff(b []byte) {
    fmt.Printf("Do something with byte len=%d\n", len(b))
}
```

What can be done?

**Comment by Glavic** [comment]
[Issue 145](https://github.com/elazarl/goproxy/issues/142) is probably the same?

**Comment by zulmaster** [comment]
Got same error.

**Comment by ErikPelli** [comment]
https://support.mozilla.org/en-US/questions/1064991

Related to https://github.com/elazarl/goproxy/issues/560
