### ISSUE TITLE
Why is ctx.Req.Body empty in OnResponse()?

### ISSUE THREAD

**Issue by Glavic** [elazarl/goproxy#183]
In `OnResponse()` I would like to view what the request body was. 
But `ctx.Req.Body` is empty, even when `ctx.Req.ContentLength` is not `0`.
What can be done?

**Comment by elazarl** [comment]
Thanks for the bug report
Can you explain how to reproduce this issue?

**Comment by Glavic** [comment]
While writing you an example code, I saw I get an error while reading body:

```
func main() {
	proxy := goproxy.NewProxyHttpServer()
	proxy.OnResponse().DoFunc(func(res *http.Response, ctx *goproxy.ProxyCtx) *http.Response {
		request_body, err := ioutil.ReadAll(ctx.Req.Body)
		if err != nil {
			log.Fatalln(err)
		}
		log.Printf("Request body is %d long, but only %d bytes shown?", ctx.Req.ContentLength, len(request_body))
		return res
	})

	log.Fatal(http.ListenAndServe(":8081", proxy))
}

func DoStuff(b []byte) {
	log.Printf("Do something with byte len=%d\n", len(b))
}
```

Where error `http: invalid Read on closed Body` is outputed.

**Comment by elazarl** [comment]
Maybe you read the body twice?

**Comment by Glavic** [comment]
This is the whole/full example, where there is no double read...

**Comment by Glavic** [comment]
@elazarl: Have you tried the example? Does it work for you?
What can be done :/

**Comment by Glavic** [comment]
Is there any other way for me to get Request body in the Response?
Tnx

**Comment by elazarl** [comment]
Hi,

I believe that you must save it in the request handler, and pass a reference to it in the context.

**Comment by 2tvenom** [comment]
Hello, 
i have same error
You have fast solution?

Thank you

**Comment by Glavic** [comment]
@2tvenom : Like @elazarl mentioned; save requests somewhere, and then use it in response.
I save request in `ctx.UserData (goproxy.ProxyCtx)`, which is `interface{}` and then just read that data in response.

**Comment by elazarl** [comment]
Hi, is there anything else you need?
If so, please reopen.
