### ISSUE TITLE
Large HTTP responses not streaming to client

### ISSUE THREAD

**Issue by bunsim** [elazarl/goproxy#184]
It seems that goproxy will not stream large HTTP responses to the client. Instead, it loads the entire response in memory before sending anything to the client.

This is causing some major issues with very large files, which cause unresponsiveness in the client and excessive memory usage at the proxy. Is this a configuration issue, or is it inherent to the way goproxy is designed?

**Comment by elazarl** [comment]
No, this is a bug.
Can you please tell me how to reproduce it?

**Comment by bunsim** [comment]
Never mind, seems like it's a bug with the 2tvenom fork.
