### ISSUE TITLE
About introducing-goproxy-light-http-proxy

### ISSUE THREAD

**Issue by suntong** [elazarl/goproxy#186]
The link on the front page for introducing-goproxy-light-http-proxy, http://ripper234.com/p/introducing-goproxy-light-http-proxy/, is gone. 

Has it been moved to somewhere else? Thx.

**Comment by elazarl** [comment]
I removed it, since this website seem to go offline soon.

**Comment by suntong** [comment]
Do you still have a copy somewhere?

**Comment by elazarl** [comment]
As far as I can see, it's still available, but without CSS.
Care to mirror it somewhere?

**Comment by suntong** [comment]
Oh, I only saw "This blog has moved to Medium", then checked over there without scrolling further down. Will put it into my personal private collection before it went away.

**Comment by elazarl** [comment]
Can you please put it online, and I'll add a link to where you add it?

**Comment by suntong** [comment]
Sorry I don't have a proper online place to mirror it either. Maybe you put it into your wiki page?
