### ISSUE TITLE
https proxy example please

### ISSUE THREAD

**Issue by suntong** [elazarl/goproxy#192]
I'm trying to learn to use `goproxy` through the example https://github.com/elazarl/goproxy/tree/master/examples/goproxy-httpdump. 

I found that it can only handle http requests, not https'. Could you provide an example that can handle https requests please? (As almost all web servers are moving away from http to https now, e.g., github, wikipedia, wordpress, etc). 

PS, by "handle https requests" I meant that none of the https requests are dumped by the current goproxy-httpdump program. 

Thanks

**Comment by suntong** [comment]
Suppose tracking https requests is impossible (or too difficult), then my next question is how to output those "Tunnel to" requests from goproxy-httpdump?

I.e., each **https** request is lead by a normal **HTTP** request of type "Tunnel to", which has the following headers:

```
CONNECT csi.gstatic.com:443 HTTP/1.1
Host: csi.gstatic.com:443
Connection: keep-alive
User-Agent: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

A SSLv3-compatible ClientHello handshake was found. Fiddler extracted the parameters below.

Version: 3.3 (TLS/1.2)
Random: ...
```

I need to dump those requests as well from goproxy-httpdump. 

Thanks

**Comment by sundy-li** [comment]
+ 1 
[https://github.com/elazarl/goproxy/blob/master/examples/goproxy-transparent/transparent.go](url)
This example is not very well...

**Comment by elazarl** [comment]
What about this example:
https://github.com/elazarl/goproxy/blob/master/examples/goproxy-eavesdropper/main.go

**Comment by suntong** [comment]
The problem is that I found `goproxy` can only handle http requests, not http**s**'. 
That was the question, and I am afraid that I wasn't able to find the answer from the `goproxy-eavesdropper` example. Maybe I'm wrong about that.

**Comment by fredcy** [comment]
I've built a simple HTTPS logging proxy on top of goproxy, at https://github.com/fredcy/proxy

**Comment by rahulwa** [comment]
I guess if you add this to your main function, it should work. It will do man-in-the-middle attacks against HTTPS.
```go
GoProxy.OnRequest(goproxy.ReqHostMatches(regexp.MustCompile("^.*:443$"))).
	HandleConnectFunc(func(host string, ctx *goproxy.ProxyCtx) (*goproxy.ConnectAction, string) {
		return goproxy.MitmConnect, host
	})
```

**Comment by fredcy** [comment]
That's pretty much what I do in my logging proxy.
https://github.com/fredcy/proxy/blob/73914b909caf97d0f92a0d9b075c3fda33197b0f/main.go#L109-L110

**Comment by suntong** [comment]
Thanks a lot @fredcy & @rahulwa, I'll look into it this weekend and get back to you...

**Comment by suntong** [comment]
This, in deed, is doing man-in-the-middle attacks against HTTPS, which is not allowed by default. 

The fiddler circumvents it by installing its own Root Certificate into the system (on Windows), @fredcy, how did you solve the problem? Thx.

**Comment by fredcy** [comment]
I imported the CA certificate embedded in goproxy into the Keystore on my MacOS client and marked it as trusted. With that done my Mac client uses the proxy without any complaints or warnings about cert problems.

The needed certificate is contained in the certs.go file.  At the time of writing it's here: https://github.com/elazarl/goproxy/blob/4327d5f85a6da046b9b4818382a3e51f795a249b/certs.go#L24-L57

I think the ca.pem file is supposed to be exactly that cert but it's out of date. I opened https://github.com/elazarl/goproxy/issues/216 about that.

**Comment by elazarl** [comment]
You are correct. CA.pem out of date.
Mind sending a PR to fix that?

**Comment by fredcy** [comment]
OK. https://github.com/elazarl/goproxy/pull/218

**Comment by suntong** [comment]
I spent time working on something else, but
looks good. :+1:
