### ISSUE TITLE
Socket IO support

### ISSUE THREAD

**Issue by MeGaPk** [elazarl/goproxy#193]
What about support socket.io?

**Comment by elazarl** [comment]
I believe supporting websockets would cover us here, won't it?

**Comment by mikegleasonjr** [comment]
Yes, are there any plans to support websockets?

**Comment by elazarl** [comment]
Yes, however I'm not free to look into it in the near future.

Apologies

**Comment by ErikPelli** [comment]
Websockets are currently supported by goproxy, so this issue can be closed
