### ISSUE TITLE
How to save the host dns ip addr?

### ISSUE THREAD

**Issue by zhangyc310** [elazarl/goproxy#194]
## Resolve hosts to ip addr ,Want  to save the ip addr, Because Resolve spends many times.

I want to replace the default dial func,  but ,how to get the tcpAddr? 

Some one help to give some detail code?

```
d := net.Dialer{LocalAddr: tcpAddr}
proxy.Tr.Dial = d.Dial
```

Thanks very much!

**Comment by lexesv** [comment]
```
ip := net.ParseIP("127.0.0.1").To4()
tcpAddr := &net.TCPAddr{IP: net.IPv4(ip[0], ip[1], ip[2], ip[3]), Port: 0}
d := net.Dialer{LocalAddr: tcpAddr}
proxy.Tr.Dial = d.Dial
```
