### ISSUE TITLE
Custom https cert file support

### ISSUE THREAD

**Issue by sundy-li** [elazarl/goproxy#196]
Could this library add Custom https cert file support?
Just like https://github.com/alibaba/anyproxy did.

**Comment by elazarl** [comment]
Yes, check out `TLSConfigFromCA(&GoproxyCa)`, and instead of `MitmConnect` use something like `&ConnectAction{Action: ConnectMitm, TLSConfig: TLSConfigFromCA(&myCA)}`

**Comment by elazarl** [comment]
apologies for the delay, didn't notice it when I first got the ticket.
