### ISSUE TITLE
is there a way to change the outgoing ip?

### ISSUE THREAD

**Issue by Misterhex** [elazarl/goproxy#198]
Hi, I have several network interfaces with various IP adresses. How can I make goproxy define which outgoing ip to send http requests to target site. Thanks!

**Comment by elazarl** [comment]
This should be done by setting a custom transport that would, e.g., open
the socket in a way the kernel would bind a specific IP to it.

**Comment by Misterhex** [comment]
I managed to bind to a specific local ip by using the following snippet below:

```
package main

import (
	"github.com/elazarl/goproxy"
	"log"
	"net"
	"net/http"
)

func main() {
	proxy := goproxy.NewProxyHttpServer()

	// 192.168.1.194 is the local ip
	// :0 denote letting the os decide on port to bind
	addr := "192.168.1.194:0"
	localAddr, err := net.ResolveTCPAddr("tcp", addr)
	if err != nil {
		panic(err)
	}

	d := net.Dialer{LocalAddr: localAddr}
	proxy.Tr.Dial = d.Dial

	proxy.Verbose = true

	log.Fatal(http.ListenAndServe(":3001", proxy))
}

```
