### ISSUE TITLE
Response header removal

### ISSUE THREAD

**Issue by gambol99** [elazarl/goproxy#205]
Hiya ... whats the reasoning/rational for deleting all the [response headers](https://github.com/elazarl/goproxy/blob/master/proxy.go#L35)? ... The reason I ask, I'm using the lib as reverse proxy, however, part of the requirement is to inject a cookie (essentially a refreshed session) back into the response. Normally I guess I'd use the OnResponse(), but because the proxy is handled in [gin](github.com/gin-gonic/gin) middleware I can't pass the gin.Context into the OnReponse method in order to retrieve the injected cookie upstream. I could delete the section of code if not required (thought that might be a breaking change) or extend the ProxyCtx to include the http.ResponseWriter and then add a [response handler](https://github.com/elazarl/goproxy/blob/master/proxy.go#L125) to inject the set-cookie into the response before they are deleted [here](https://github.com/elazarl/goproxy/blob/master/proxy.go#L137)? ...

**Comment by ErikPelli** [comment]
We don't delete all the response headers :/
We just delete the headers related to the porxy, like the proxy authentication, inside `RemoveProxyHeaders()`.
Closing this issue.
