### ISSUE TITLE
`removeProxyHeaders` should be optional

### ISSUE THREAD

**Issue by AlmogBaku** [elazarl/goproxy#207]
In case I want to chain proxies, this function just remove any authentication between me and the chained proxy server

**Comment by AlmogBaku** [comment]
@elazarl what do you think?

**Comment by paambaati** [comment]
**BUMP!**

**Comment by elazarl** [comment]
@AlmogBaku I don't think so. The proxy header should be added back by the transport, doesn't it?

Apologize for the delay, too busy lately.

**Comment by AlmogBaku** [comment]
@elazarl actually no, you removing these headers in the `removeProxyHeaders()` method in the goproxy package (`proxy.go:74`)

**Comment by AlmogBaku** [comment]
BTW, i'll appreciate your response in Slack.. trying to reach you there for a while

**Comment by ErikPelli** [comment]
Currently there is a configurable option to not call it. Closing this issue.
