### ISSUE TITLE
goproxy doesn't work with go 1.8

### ISSUE THREAD

**Issue by MosheWagner** [elazarl/goproxy#208]
When using goproxy with go 1.8, the following panic occurs:
```panic: Error parsing builtin CA x509: RSA key missing NULL parameters

goroutine 1 [running]:
github.com/elazarl/goproxy.init.1()
        C:/Users/moshew/go/src/github.com/elazarl/goproxy/certs.go:10 +0x1ea
github.com/elazarl/goproxy.init()
        C:/Users/moshew/go/src/github.com/elazarl/goproxy/signer.go:88 +0x32a
main.init()
        C:/temp/test/main.go:16 +0x50
```

To reproduce simply build and run:
```
package main

import (
	"fmt"

	"github.com/elazarl/goproxy"
)

func a() {
	proxy := goproxy.NewProxyHttpServer()
	fmt.Printf("%v\n", proxy)
}

func main() {
}
```

The same code works with go 1.7.5

**Comment by mattweidner** [comment]
This issue appears to be caused an upstream change in the go 1.8 standard library [crypto/x509](https://github.com/golang/go/commit/59aeac20c0412442848982a9287b4bab66c25682) that requires regenerating the certificate. I was able to get this working with go 1.8 by regenerating the root CA cert and private key using openssl.
```
openssl genrsa -out rootCA.key 2048
openssl req -x509 -new -nodes -key rootCA.key -sha256 -days 90 -out rootCA.pem
```
Then cut and paste the cert and private key into goproxy/certs.go

*Note that in this example, the generated cert is only good for 90 days and a 2048-bit key is probably overkill. You may want to adjust those numbers for your use case.*

**Comment by erikdubbelboer** [comment]
This is the same issue as #188 which didn't get fixed. @elazarl any idea when this will be fixed?

**Comment by dims** [comment]
@elazarl @erikdubbelboer Kubernetes folks are waiting as well https://github.com/kubernetes/kubernetes/issues/38228

**Comment by elazarl** [comment]
Can someone please test this issue, and verify the new certificate is indeed good?

**Comment by mattweidner** [comment]
@elazarl works great for me. thanks!

**Comment by fredcy** [comment]
The work done for this did not seem to update the ca.pem file in this repo.
