### ISSUE TITLE
How to use this with Nginx

### ISSUE THREAD

**Issue by bporter2387** [elazarl/goproxy#214]
Is there a way to pass a request from Nginx -> goproxy -> backend service (uwsgi). I want to capture the request and headers, do an auth lookup, and continue proxying the request to a uwsgi backend once the request is authorized.

When I listen on :80 and proxy_pass to localhost:8080 using one of the examples, I keep getting "This is a proxy server. Does not respond to non-proxy requests"

Any insight to this would greatly be appreciated!

-Brett

**Comment by elazarl** [comment]
Goproxy it's a regular proxy, ngnix uses a reverse proxy.

**Comment by bporter2387** [comment]
I ended up using Gin to intercept the request instead. Thanks

**Comment by perlun** [comment]
(For reference, Gin: https://github.com/gin-gonic/gin)
