### ISSUE TITLE
CA certificate files ca.pem and key.pem no longer match cert.go

### ISSUE THREAD

**Issue by fredcy** [elazarl/goproxy#216]
I assume that the ca.pem and key.pem files in the root are supposed to be those corresponding to what is in certs.go, but they no longer match because of https://github.com/elazarl/goproxy/commit/c4fc26588b6ef8af07a191fcb6476387bdd46711. Should ca.pem and key.pem be updated to match, or perhaps removed if we are supposed to copy/paste the cert info from certs.go when obtaining the cert to install in a client?

**Comment by elazarl** [comment]
They should be updated, will do. Thanks
