### ISSUE TITLE
Does it support reverse proxy?

### ISSUE THREAD

**Issue by shellus** [elazarl/goproxy#221]
Use the following code to test
```

func main() {
	proxy := goproxy.NewProxyHttpServer()
	proxy.Verbose = true

	proxy.OnRequest().DoFunc(
		func(r *http.Request, ctx *goproxy.ProxyCtx) (*http.Request, *http.Response) {
			host := "www.google.com"

			log.Println(r.Header.Get("Host"))

			r.Header.Set("Host", host)
			r.Host = host
			r.URL.Host = host
			r.URL.Scheme = "https"
			return r, nil
		})

	http.Handle("/", proxy)

	err := http.ListenAndServe(":8080", nil)

	if err != nil {
		log.Fatal(err)
	}
}

```

i put it `http://127.0.0.1` reverse proxy to `www.google.com`, But encountered the following error.

github.com/elazarl/goproxy/proxy.go line: 104
```
		if !r.URL.IsAbs() {
			proxy.NonproxyHandler.ServeHTTP(w, r)
			return
		}
```

If I delete the three lines of code, you can use goproxy reverse proxy to Google. This will greatly improve the use of goproxy scenes.

This is similar to the nginx reverse proxy effect that can be used to add code to add logic. If it can be, would be great

**Comment by elazarl** [comment]
If anyone is able to translate it, I'll be halt to answer, and you can
translate it back :-)

**Comment by shellus** [comment]
@elazarl I have finished the translation, please give me advice

**Comment by shellus** [comment]
@elazarl hi

**Comment by shytikov** [comment]
BTW, I'm also interested in reverse proxy functionality. 

Is it possible to make `NonproxyHandler` "overridable"?

**Comment by shytikov** [comment]
Ok, it was late night, so I didn't check myself. But yes, it is possible to change meaning of `NonproxyHandler` on creation of `goproxy`, something like that:

```
	proxy := goproxy.NewProxyHttpServer()
	proxy.Verbose = true

	proxy.NonproxyHandler = http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		// Reverse proxy code goes here
	})
``` 

Not sure is it best practice or not, but it should work without making changes to the core library.

**Comment by elazarl** [comment]
Hi,

I'm hesitating to allow reverse proxy usage for goproxy, since there are many excellent reverse proxies for Go.

Is there a reason you're not using them?

**Comment by shellus** [comment]
You are right, and now i am using go with the http reverse proxy, it works fine
https://github.com/golang/go/blob/master/src/net/http/httputil/example_test.go

**Comment by ahmetb** [comment]
For anyone interested, here's a small hack to make it work like a "reverse proxy".

It seems (currently) the only check to detect if a request is "proxy" request or not is checking `req.URL.IsAbs()` which only checks `URL.Schema != ""`. Since you’re most likely to be implementing a HTTP-based reverse-proxy, you can apply a hack like this:

```
func setURLScheme(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		r.URL.Scheme = "http"
		next.ServeHTTP(w, r)
	})
}
```

Then wrap the goproxy handler like `setURLScheme(goproxy.NewProxyHttpServer())`.
