### ISSUE TITLE
NewConnectDialToProxy does not forward non-standard ports correctly.

### ISSUE THREAD

**Issue by zanitee** [elazarl/goproxy#223]
When using NewConnectDialToProxy() to forward requests through a upstream proxy server, If the request is using a non standard port in the URL such as "http://example.com:9000/path" the request will fail.

The upstream server seems to receive the host:port only and no Path/scheme.

Example to recreate bug.
Set a upstream proxy, then start the proxy and try visiting a URL which is listening on a non standard HTTP port. I consider this to be a pretty big bug as it renders many uses useless.

```
func main() {
	proxy := goproxy.NewProxyHttpServer()

	// We change the proxy Transport method to route all connections though our proxy.
	proxyURL := "http://user:pass@127.0.0.1:8080"
	proxy.Tr.Dial = forward(proxyURL, proxy)
	
	log.Fatal(http.ListenAndServe(":8080", proxy))
}

// forward is a custom dialer which forwards all requsts to a proxy server.
func forward(proxyURL string, proxy *goproxy.ProxyHttpServer) func(network, addr string) (net.Conn, error) {
	u, err := url.Parse(proxyURL)
	if err != nil {
		fmt.Println("failed to parse upstream server:", err)
	}

	// Return the Dial'er.
	return func(network, addr string) (net.Conn, error) {
		// Prevent toAddr proxy from being re-directed
		if u.Host == addr {
			return net.Dial(network, addr)
		}
		dialer := proxy.NewConnectDialToProxy(proxyURL)
		if dialer == nil {
			panic("nil dialer, invalid uri?")
		}
		return dialer(network, addr)
	}
}
```

**Comment by rahulwa** [comment]
I believe that `NewConnectDialToProxy` function doesn't do "Proxy-Authorization". 
i don't know, it solves your problem or not, but you can check out https://github.com/rahulwa/camouflage/blob/master/proxy/proxy.go#L171-L238.

**Comment by zanitee** [comment]
Thanks @rahulwa. You're right but I had already patched this.

When requesting normal URLs like http://example.com everything is working fine. But if we have appended port number the requests will fail.

**Comment by rahulwa** [comment]
@zanitee i just tried that it works fine for me. 
I tried  with [this](https://github.com/rahulwa/camouflage/blob/master/examples/main/mainSimple.go).

**Comment by zanitee** [comment]
@rahulwa Thanks I'll actually take a look at your repo.

When you was testing which URL was you trying to visit via your browser? As i said it only occurs when visiting urls with non standard port.

For example try visiting this URL: http://portquiz.net:8080/

**Comment by rahulwa** [comment]
I also tried with your above given example, it works fine.

```
package main

import (
	"github.com/elazarl/goproxy"
	"net"
	"net/url"
	"net/http"
	"log"
	"fmt"
)


func main() {
	proxy := goproxy.NewProxyHttpServer()

	// We change the proxy Transport method to route all connections though our proxy.
	proxyURL := "http://127.0.0.1:8081"
	proxy.Tr.Dial = forward(proxyURL, proxy)

	log.Fatal(http.ListenAndServe(":8080", proxy))
}

// forward is a custom dialer which forwards all requsts to a proxy server.
func forward(proxyURL string, proxy *goproxy.ProxyHttpServer) func(network, addr string) (net.Conn, error) {
	u, err := url.Parse(proxyURL)
	if err != nil {
		fmt.Println("failed to parse upstream server:", err)
	}

	// Return the Dial'er.
	return func(network, addr string) (net.Conn, error) {
		// Prevent toAddr proxy from being re-directed
		if u.Host == addr {
			return net.Dial(network, addr)
		}
		dialer := proxy.NewConnectDialToProxy(proxyURL)
		if dialer == nil {
			panic("nil dialer, invalid uri?")
		}
		return dialer(network, addr)
	}
}
```

```
$ curl -ix 127.0.0.1:8080 -p http://portquiz.net:8080/
HTTP/1.0 200 OK

HTTP/1.1 200 OK
Date: Wed, 10 May 2017 17:47:29 GMT
Server: Apache
X-Powered-By: PHP/5.4.45-0+deb7u8
Vary: Accept-Encoding
Content-Length: 50
Content-Type: text/html

Port 8080 test successful!
Your IP: XXXXXXXX

**Comment by zanitee** [comment]
@rahulwa You're right. How stupid of me. It turns out the problem was the upstream server!

I tried a different upstream proxy and it works fine. Thank you for your time. I will checkout your camoflauge repo too :D
