### ISSUE TITLE
Original Response always gets cancelled/closed, but i want to read it after.

### ISSUE THREAD

**Issue by sarim** [elazarl/goproxy#224]
What i'm trying to do is saving/dumping certain responses. Kinda similar to httpdump example, but its different, i want to download the request, but i don't want to send request to client/user. Sounds confusing but the code will clarify.

```go
proxy.OnResponse().DoFunc(
    func(resp *http.Response, ctx *goproxy.ProxyCtx) *http.Response {
        if resp != nil {
            if checkType(resp.Header.Get("Content-Type")) {
                go func() {
                    f, _ := os.Create("testfile")
                    _, err := io.Copy(f, resp.Body)
                    if err != nil {
                        log.Println(err)
                    }
                    f.Close()
                }()
                return goproxy.NewResponse(ctx.Req, goproxy.ContentTypeText, 200, "Download Queued in Server")
            }
        }
        return resp
    })

```

What happens is client immediately gets `Download Queued in Server` reply, and don't need to wait for the response to download. Meanwhile i run a goroutine to asynchronously download the response to a file. User/client can come at a later time to get the file.

Now the problem is goproxy/http destroys the request and response as soon as i return "Download Queued in Server". See proxy.go line 126. `defer origBody.Close()`
So when my goroutine runs io.Copy it gets error: `http: read on closed response body`

Now how can i achieve what i want? :P

**Comment by rahulwa** [comment]
You can use `dumpresponse` function from `httputil` package.  [Like this](https://github.com/rahulwa/camouflage/blob/master/proxy/proxy.go#L148).

**Comment by sarim** [comment]
@rahulwa dumpresponse won't work, its a simple convenient function to read the resp.Body. It is similar to what i'm doing.  My problem is i'm doing it in a goroutine. If i discard the  goroutine and run my codes as blocking, it works. My problem isn't with reading the response, rather the response is being closed before i can read it asynchronously.

**Comment by sarim** [comment]
I solved it by using a custom Roundtripper.

```go
func (r BoxRoundTrip) RoundTrip(req *http.Request, ctx *goproxy.ProxyCtx) (*http.Response, error) {
	newReq := req.WithContext(context.Background())
	resp, err := r.proxy.Tr.RoundTrip(newReq)
	if resp.Body != nil {
		resp.Body = ioutil.NopCloser(resp.Body)
	}
	return resp, err
}
`

NopCloser prevents the response body from closing and copying and replacing request context prevents the request from canceling.
