### ISSUE TITLE
Does goproxy.UrlMatches work?

### ISSUE THREAD

**Issue by deepakkb** [elazarl/goproxy#229]
Following blocks calls to all https calls to integration1-sse.abc.com
proxy := goproxy.NewProxyHttpServer()
proxy.OnRequest(goproxy.ReqHostMatches(regexp.MustCompile("^*integration1-sse.abc.com:443$"))).HandleConnect(goproxy.AlwaysReject)
verbose := flag.Bool("v", true, "should every proxy request be logged to stdout")
addr := flag.String("addr", ":12345", "proxy listen address")
flag.Parse()
proxy.Verbose = *verbose
log.Fatal(http.ListenAndServe(*addr, proxy))

But I want to block some urls having "objectstore". Hence I tried following which never worked for me.
proxy := goproxy.NewProxyHttpServer()
**proxy.OnRequest(goproxy.ReqHostMatches(regexp.MustCompile("^.*objectstore.*$"))).HandleConnect(goproxy.AlwaysReject)**
verbose := flag.Bool("v", true, "should every proxy request be logged to stdout")
addr := flag.String("addr", ":12345", "proxy listen address")
flag.Parse()
proxy.Verbose = *verbose
log.Fatal(http.ListenAndServe(*addr, proxy))

Any ideas what I am doing wrong?

**Comment by nooges** [comment]
Your regex is incorrect, it should be: "^.*objectstore.*$"

**Comment by lived-tw** [comment]
I know this is an old thread but I just want to share the finding regarding to this issue.

```go
proxy.OnRequest(goproxy.ReqHostMatches(regexp.MustCompile("^.objectstore.$"))).HandleConnect(goproxy.AlwaysReject)
```

need to replaced by 

```go
proxy.OnRequest(goproxy.UrlMatches(regexp.MustCompile("^.objectstore.$"))).Do(some func implement goproxy.FuncReqHandler)
```

If you want to do some filtering by URL.

Hereunder are code piece from proxy.go:
```go
type ProxyHttpServer struct {
	// session variable must be aligned in i386
	// see http://golang.org/src/pkg/sync/atomic/doc.go#L41
	sess int64
	// KeepDestinationHeaders indicates the proxy should retain any headers present in the http.Response before proxying
	KeepDestinationHeaders bool
	// setting Verbose to true will log information on each request sent to the proxy
	Verbose         bool
	Logger          *log.Logger
	NonproxyHandler http.Handler
	reqHandlers     []ReqHandler
	respHandlers    []RespHandler
	httpsHandlers   []HttpsHandler
	Tr              *http.Transport
	// ConnectDial will be used to create TCP connections for CONNECT requests
	// if nil Tr.Dial will be used
	ConnectDial func(network string, addr string) (net.Conn, error)
}
```
There are 3 kind of useful filters. 
proxy.OnRequest(...).**HandleConnect(...)** put the filters into httpsHandlers slice, which are called **WITHOUT**  URL.Path.

The only place for you to filter by URL.Path (and of course URL.Host) is reqHandlers, which is placed by proxy.OnRequest(...).**Do(...)**.

**Comment by elazar-lb** [comment]
Thanks @live-tw, can you please put that into a PR, maybe in the readme?

**Comment by lived-tw** [comment]
Hi @elazar-lb, just created the PR and sorry for the delay (a newbie here, just want to make sure that I did nothing wrong.)

**Comment by ErikPelli** [comment]
https://github.com/elazarl/goproxy/pull/337 added a clarification to the readme about this issue. Closing.
