### ISSUE TITLE
Handling non-SNI requests

### ISSUE THREAD

**Issue by SmashGuy2** [elazarl/goproxy#231]
I'm using abourget's fork of goproxy as a transparent intercept proxy and it works great for everything except non-SNI clients (specifically, an Amazon Fire TV).

**Does anyone have any ideas on how to handle https requests that do not include an SNI extension?** 

Some ideas:

1. Configure deep packet inspection in the firewall (slow, may not work for some clients due to fragmentation)
2. Send a dummy certificate back to the client. I think this will work, but I can't figure out where to redirect the original request to. Abourget's fork uses inconshrevable's virtual hosting package and it appears the original IP address is not being detected after iptables forwards the port.
3. Try to sniff the local DNS and guess at a host. Doesn't seem very reliable.

Thanks
SG

**Comment by elazarl** [comment]
You have to fully mitm them, and look at the header

**Comment by SmashGuy2** [comment]
Thanks for your reply. I've been trying to figure out how to MITM a non-SNI request, but I'm a little stumped. Any advice you can offer would be greatly appreciated.

In the /goproxy-transparent example, the appropriate section of code can be found starting on line 87 of transparent.go:

`		go func(c net.Conn) {
			tlsConn, err := vhost.TLS(c)
			if err != nil {
				log.Printf("Error accepting new connection - %v", err)
			}
			**if tlsConn.Host() == "" {
				log.Printf("Cannot support non-SNI enabled clients")
				return
			}**
			connectReq := &http.Request{
				Method: "CONNECT",
				URL: &url.URL{
					Opaque: tlsConn.Host(),
					Host:   net.JoinHostPort(tlsConn.Host(), "443"),
				},
				Host:   tlsConn.Host(),
				Header: make(http.Header),
			}
			resp := dumbResponseWriter{tlsConn}
			proxy.ServeHTTP(resp, connectReq)`

The check is made to tlsConn.Host() (which sniffs the SNI extension, not present in this case) and when that fails the request is rejected.

The two problems I've encountered are:

1. How do we know the original destination without the SNI header? I've dumped the tlsConn object and can't find any traces of the original IP address or a host. Without that, goproxy doesn't know where to connect. BTW, I'm using goproxy as a transparent intercept configuration, using iptables to redirect the packets from the incoming interface.

2. How do we format a TLS certificate that the client won't reject? I assume we have to attach some domains that will wildcard match the intended recipient, correct?

Thanks again and sorry if these are obvious questions. I'm new to this but am slowly figuring it out.

**Comment by SmashGuy2** [comment]
Looks like #1 might be doable by using the TPROXY module in iptables. This may preserve the destination ip address in the packet, allowing us to forward the connection to the original host. Still working on it...

**Comment by elazarl** [comment]
Sounds like a good plan.
Let us know when you're done

**Comment by SmashGuy2** [comment]
No luck after two days so far. Goproxy never sees an incoming connection when I use tproxy to reroute HTTPS requests to it. Goproxy is listening for https on 0.0.0.0:8889 and I have confirmed that it does receive requests when I try to hit it directly from another computer.

Goproxy and is set up on a dedicated machine in between my router and the internet, on its own subnet. All traffic passes through it (ie: router uses it as the gateway).

My iptable rules look like this:

`
# Clean old firewall
iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X

# Set default policies
iptables -P INPUT DROP
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT

# Marks outbound traffic to howsmyssl.com to make it easier to find in the log.
iptables -t mangle -A PREROUTING --destination 104.196.190.195 -j MARK --set-mark 0xc7

# Default rules. These just allow everything to work without any proxy interception.
iptables -A INPUT -i br0 -j ACCEPT
iptables -A INPUT -i lo -j ACCEPT

# Try to get the outbound request to redirect to our proxy port. Right now it's being forwarded.

# If this line is commented out, DNS fails
iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT

# These are the tproxy rules which are supposed to redirect traffic to a local port without
# overwriting the destination IP address
iptables -t mangle -N DIVERT

# This forces all port 443 traffic to the new DIVERT table
iptables -t mangle -A PREROUTING -p tcp --dport 443 -j DIVERT

# Mark the traffic
iptables -t mangle -A DIVERT -j MARK --set-mark 1
iptables -t mangle -A DIVERT -j ACCEPT

# reroute any marked traffic to the loopback device
ip rule add fwmark 1 lookup 100
ip route add local 0.0.0.0/0 dev lo table 100

iptables -t mangle -A PREROUTING -p tcp --dport 443 -j TPROXY --tproxy-mark 0x1/0x1 --on-port '8889'

# Masquerade outgoing packets
iptables -t nat -A POSTROUTING -o eth0.101 -j MASQUERADE
`

And here's some sample packet debug output when I try to hit an SSL site. You can see here that the https request is making it to the DIVERT table and getting marked.

`
IN=br0 OUT= SRC=192.168.101.154 DST=104.196.190.195 LEN=52 TOS=0x00 PREC=0x00 TTL=127 ID=15422 PROTO=TCP SPT=51584 DPT=443
        raw PREROUTING NFMARK=0x0 (0xc184000)
                ACCEPT
 
       # ignore this, I just mark the packet with 0xc7 to make it easy to find in the log
        mangle PREROUTING (#1) NFMARK=0x0 (0xc184000)
                ip 0.0.0.0/0.0.0.0 -> 104.196.190.195/255.255.255.255
                => MARK {'set-xmark': '0xc7/0xffffffff'}

        mangle PREROUTING (#2) NFMARK=0xc7 (0xc7)
                tcp 0.0.0.0/0.0.0.0 -> 0.0.0.0/0.0.0.0 tcp:{'dport': '443'}
                => ^DIVERT^
        mangle DIVERT (#1) NFMARK=0xc7 (0xc7)
                ip 0.0.0.0/0.0.0.0 -> 0.0.0.0/0.0.0.0
                => MARK {'set-xmark': '0x1/0xffffffff'}
        mangle DIVERT (#2) NFMARK=0x1 (0x1)
                => ACCEPT
        nat PREROUTING NFMARK=0x1 (0x1)
                ACCEPT
        mangle INPUT NFMARK=0x1 (0x1)
                ACCEPT
        filter INPUT (#2) NFMARK=0x1 (0x1)
                ip 0.0.0.0/0.0.0.0 -> 0.0.0.0/0.0.0.0
                => ACCEPT
        nat INPUT NFMARK=0x1 (0x1)
                ACCEPT
`

For comparison, here is the same packet when I use regular NAT routing (which works):

`
IN=br0 OUT= SRC=192.168.101.154 DST=104.196.190.195 LEN=40 TOS=0x00 PREC=0x00 TTL=127 ID=15455 PROTO=TCP SPT=52663 DPT=443
        raw PREROUTING NFMARK=0x0 (0x46887200)
                ACCEPT
        mangle PREROUTING NFMARK=0x0 (0x46887200)
                ACCEPT
        mangle INPUT NFMARK=0x0 (0x46887200)
                ACCEPT
        filter INPUT (#1) NFMARK=0x0 (0x46887200)
                ip 0.0.0.0/0.0.0.0 -> 0.0.0.0/0.0.0.0
                => ACCEPT
`

**Comment by SmashGuy2** [comment]
A little more progress. I've determined that the following rule near the end of the iptables list above was never being hit:

>iptables -t mangle -A PREROUTING -p tcp --dport 443 -j TPROXY --tproxy-mark 0x1/0x1 --on-port '8889'

So I'm guessing the port of the original request was not being changed from 443 to 8889. This makes sense, because the mangle PREROUTING rule was already accepted before. To test this, I changed the listening port of goproxy to 443. Any direct request to a domain using that port (www.example.com:443) then resulted in an endless loop. I can't quite explain what's happening here, but clearly the request isn't being sent to the new port.

I modified the rule to:

>iptables -t mangle -A DIVERT -p tcp --dport 443 -j TPROXY --tproxy-mark 0x1/0x1 --on-port '8889'

A trace confirms that the rule is being triggered now:

>IN=br0 OUT= SRC=192.168.101.154 DST=104.196.190.195 LEN=52 TOS=0x00 PREC=0x00 TTL=127 ID=15741 PROTO=TCP SPT=55534 DPT=443
>        raw PREROUTING NFMARK=0x0 (0x24cf7e00)
>                ACCEPT
>        mangle PREROUTING (#1) NFMARK=0x0 (0x24cf7e00)
>                tcp 0.0.0.0/0.0.0.0 -> 0.0.0.0/0.0.0.0 tcp:{'dport': '443'}
>                => DIVERT
>        mangle DIVERT (#1) NFMARK=0x0 (0x24cf7e00)
>                ip 0.0.0.0/0.0.0.0 -> 0.0.0.0/0.0.0.0
>                => MARK {'set-xmark': '0x1/0xffffffff'}
>        mangle DIVERT (#2) NFMARK=0x1 (0x1)
>                tcp 0.0.0.0/0.0.0.0 -> 0.0.0.0/0.0.0.0
>                => TPROXY {'on-port': '8889', 'on-port on-ip tproxy-mark': '0x1/0x1', 'on-port on-ip': '0.0.0.0'}

I can also confirm that the ip route appears to be working correctly. The following command shows that the requested ip address is being routed to dev lo (localhost):

>root $ ip -s route get 104.196.190.195  mark 1
>local 104.196.190.195 dev lo  src 104.196.190.195  mark 1

So I'm not sure where this leaves me. TLS packets seem to be redirected to port 8889 and the proxy is listening there (direct connections to the client machine - http://192.168.101.1:8889 - appear in the log). 

But the proxy is just not responding. Any ideas?

**Comment by SmashGuy2** [comment]
Could the problem lie with the Go Net.Listener() function not accepting the packets because it believes they are destined for a different ip address?

**Comment by SmashGuy2** [comment]
Ok, the problem was with the kernel. TProxy works. A special unix socket listener has to be used to receive the incoming connections, but it works.

**Comment by odg0318** [comment]
@SmashGuy2  Do you have some codes you worked before?
