### ISSUE TITLE
NewCounterEncryptorRandFromKey Does Not Support ECDSA Keys

### ISSUE THREAD

**Issue by dmayer** [elazarl/goproxy#233]
Hi,

I am looking to use goproxy using an ECDSA-based CA. It appears this is not currently possible since `NewCounterEncryptorRandFromKey` does not support ECDSA private keys. I assume the purpose for using `CounterEncryptorRand` is to have repeatable key and certificate generation for each connection to a particular host? 

Is there a particular reason that ECDSA keys do not work for this using, e.g., the output from `x509.CreateCertificate` where `x509.MarshalPKCS1PrivateKey` is used for RSA?

Thanks!

**Comment by ErikPelli** [comment]
ECDSA is now currently supported in the master branch
