### ISSUE TITLE
update gopkg.in tag

### ISSUE THREAD

**Issue by ddo** [elazarl/goproxy#234]
I was using

```go
import "gopkg.in/elazarl/goproxy.v1"
```

 as the README installation guild. But the v1 tag is outdated https://github.com/elazarl/goproxy/releases/tag/v1.0

i realized that because i got the certs error stuff which was fixed months ago
Hope it's help people who confused like me

using master branch repo should be fine
```go
import "github.com/elazarl/goproxy"
```

**Comment by ErikPelli** [comment]
We don't ue gopkg.in anymore, yes, use directly the import you specified

**Comment by ErikPelli** [comment]
😆 I joined last week to help with the maintenance of the project
