### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ssut** [elazarl/goproxy#240]
Hasn't been a new commit in almost a half year. There are a bunch of pull requests, which are ready to be merged, but they are not. Is this project dead?

**Comment by elazarl** [comment]
Nope. Not dead.

However, I don't think the project would change much in the near future. As
I intend to keep backwards compatibility, and hesitate to add new features.

Moreover, unfortunately, goproxy is not my primary focus now, as I intend
to try better ideas, while breaking the API, with goproxy2.

Thanks for taking a look at this project.

**Comment by ssut** [comment]
Thanks @elazarl.
