### ISSUE TITLE
is this similar to nginx?

### ISSUE THREAD

**Issue by satyashanmuka** [elazarl/goproxy#244]
I ran standalone program with below code:

package main

import (
    "github.com/goproxy-master"
    "log"
    "net/http"
)

func main() {
    proxy := goproxy.NewProxyHttpServer()
    proxy.Verbose = true
    log.Fatal(http.ListenAndServe(":8080", proxy))
    proxy.OnRequest().DoFunc(func(r *http.Request,ctx *goproxy.ProxyCtx) (*http.Request, *http.Response){
    r.Header.Set("X-GoProxy","1")
    return r, nil
})
}

localhost:8080 has a proxy running, **but not sure how to route my actual requests via this proxy running on port 8080**

**Comment by satyashanmuka** [comment]
How to specify the target urls , I wish to access via this proxy programmatically, any example  I could refer to(not via browser)

**Comment by elazarl** [comment]
curl --proxy localhost:8080 google.com

**Comment by satyashanmuka** [comment]
Thanks, will try this and how to invoke the same in the GO code via a httprequesy call programmatically?

**Comment by elazarl** [comment]
Can you open a bug about (2)?
