### ISSUE TITLE
Ability to know whether CONNECT is HTTP or HTTPS

### ISSUE THREAD

**Issue by mogronalol** [elazarl/goproxy#246]
Some clients use HTTP with CONNECT as well as using it for HTTPS tunneling. I have been trying to see if I could look at the request at runtime to determine the correct `connectAction`. First, I tried fiddling around, and created a function like this:

```golang
var chooseConnectAction goproxy.FuncHttpsHandler = func(host string, ctx * goproxy.ProxyCtx) (*goproxy.ConnectAction, string) {
    if strings.HasSuffix(host, ":80") {
        return goproxy.HTTPMitmConnect, host
    } else {
        return goproxy.MitmConnect, host
    }
}
```

It kind of works, if you assume HTTP on port 80 only, otherwise HTTPS. 

In reality, HTTP or HTTPS could work on lots of different ports, so I actually need to detect this in a more reliable manner.

I tried:

1. Looking at `ctx.Req.TLS`: I expected this to be nil if HTTP otherwise not nil. It's actually always nil.
2. Looking at the URL scheme, but this isn't available on the request object.

My networking skills are a little basic, so maybe there is something else that could be done that I've not thought of? If anyone has a suggestion I could give it a go a raise a PR, or maybe it is not possible?

**Comment by elazarl** [comment]
How would you know that?

It depends on what the client would send, and the client didn't yet send
anything.

What you might be able to do, is to try and see if the IP requested by the
client supports HTTP, and if it does assume he'll try HTTP.

**Comment by mogronalol** [comment]
This has come from this upstream issue:

https://github.com/reactor/reactor-netty/issues/159

Essentially when their client uses a proxy it always uses CONNECT even if HTTP. The problem they have is that Hoverfly (GoProxy) automatically assumed HTTPS which causes a request to hang if it's HTTP.

Initially, I thought this behavior was strange (for their client to use CONNECT for HTTP instead of HTTPS tunneling), but it seems that it is valid.

So then the problem came trying to figure out how to get GoProxy to choose the correct `connectAction` based on the request.

If you are saying that at this point in the CONNECT flow the client hasn't yet sent any data, so there's no way of knowing, then the problem has gone back full circle. This leaves the only option to be for the user of the proxy to configure which ports will be HTTP and HTTPS explicitly?

**Comment by elazarl** [comment]
Indeed, for "curl -p http://" and for "curl --proxy X https://...". the
proxy is receiving the same CONNECT request.

Typically, port 80 means HTTP and port 443 means HTTPS, but as you noted,
you can't always know that.

You can do things like cache the first few bytes of the request sent, and
decide what to do by the content.

Maybe this code should go to goproxy, maybe as an extension to Hijack. Not
sure.

**Comment by mogronalol** [comment]
Thanks for your help. I will look at peeking the initial bytes.

**Comment by JensRantil** [comment]
I think this can be closed, right?
