### ISSUE TITLE
请问下账号密码验证以及客户端IP限制要怎么加？

### ISSUE THREAD

**Issue by ahkimkoo** [elazarl/goproxy#250]
请问下账号密码验证以及客户端IP限制要怎么加？

**Comment by elazarl** [comment]
Hi,

Sorry I don't speak Chinese.

Can you ask someone to translate it to English?

**Comment by zqhong** [comment]
@elazarl 
Hi, elazarl:
He just asks two questions. One is how to set up goproxy with basic username and password authentication, another is how to adding IP whitelist for filter unwelcome client.

**Comment by zqhong** [comment]
@ahkimkoo 

refer #52 
用户名密码验证的问题，请参考 #52

**Comment by ErikPelli** [comment]
https://github.com/elazarl/goproxy/issues/52 contains the solution for this issue. Closing.
