### ISSUE TITLE
Adding authentication

### ISSUE THREAD

**Issue by iselind** [elazarl/goproxy#251]
I cannot find any examples of how i would using this proxy handle auth challenges, both basic and Digest preferably, so that the client doesn't have to worry about credentials.

Are there any such examples?
Is this even supported?

**Comment by twitchyliquid64** [comment]
I do this: Does this point you in the right direction?

```go

// Basic returns a basic HTTP authentication handler for requests
//
// You probably want to use auth.ProxyBasic(proxy) to enable authentication for all proxy activities
func Basic(realm string, f func(ctx *goproxy.ProxyCtx, user, passwd string) (bool, map[string]interface{})) goproxy.ReqHandler {
	return goproxy.FuncReqHandler(func(req *http.Request, ctx *goproxy.ProxyCtx) (*http.Request, *http.Response) {
		if !checkRequestAuthentication(req, ctx, f) {
			return nil, basicUnauthorizedResponse(req, realm)
		}
		return req, nil
	})
}

// BasicConnect returns a basic HTTP authentication handler for CONNECT requests
//
// You probably want to use auth.ProxyBasic(proxy) to enable authentication for all proxy activities
func BasicConnect(realm string, f func(ctx *goproxy.ProxyCtx, user, passwd string) (bool, map[string]interface{})) goproxy.HttpsHandler {
	return goproxy.FuncHttpsHandler(func(host string, ctx *goproxy.ProxyCtx) (*goproxy.ConnectAction, string) {
		if !checkRequestAuthentication(ctx.Req, ctx, f) {
			ctx.Resp = basicUnauthorizedResponse(ctx.Req, realm)
			return goproxy.RejectConnect, host
		}
		return goproxy.OkConnect, host
	})
}

// SetupProxyAuthentication will force HTTP authentication before any request to the proxy is processed.
func SetupProxyAuthentication(proxy *goproxy.ProxyHttpServer, realm string, users []User) {
	f := func(ctx *goproxy.ProxyCtx, user, passwd string) (bool, map[string]interface{}) {
		sha1Hash := fmt.Sprintf("%x", sha256.Sum256([]byte(passwd)))
		for _, usr := range users {
			if usr.Username == user && usr.Password == sha1Hash {
				return true, map[string]interface{}{}
			}
		}
		return false, nil
	}

	proxy.OnRequest().Do(Basic(realm, f))
	proxy.OnRequest().HandleConnect(BasicConnect(realm, f))
}
```

**Comment by twitchyliquid64** [comment]
Oh gawd I wrote that a few years ago, thats horrible code.

The take away is you can use `OnRequest()` with `HandleConnect` and `Do` to intercept and check all requests.

**Comment by elazarl** [comment]
Do you have an idea how to make it easier in the library?

**Comment by iselind** [comment]
What i would like is that my application can access the proxy unauthenticated, my project is just a prototype at this point. The proxy should handle both Basic and Digest authentication towards the server my clients try to access throught the proxy. Most servers will probably enforce Digest while some could possibly require Basic having no support for Digest.

I'll take a look at the documentation for `OnRequest`, `HandleConnect`, and `Do`.

**Comment by iselind** [comment]
As i understand it the different functions are used as such
- `OnRequest` - Used to specify conditions for a handler to be relevant.
- `HandleConnect` - See if connection from client should be let through.
- `Do` - Change the request before it's sent on to the server.

Is this a correct summary, am i missing something?

I cannot see which of these would allow me to catch the auth challenge and resend request with proper credentials. I need the auth challenge to know if the server require Basic or Digest authentication.

**Comment by moooofly** [comment]
Hi, I need Digest authentication too, any progress?

**Comment by iselind** [comment]
Nothing seems to happen here, closing issue for now. If anyone disagrees, please re-open.
