### ISSUE TITLE
DoFunc was handled serially?

### ISSUE THREAD

**Issue by leafyongzhong** [elazarl/goproxy#253]
Hi,I found that log in DoFunc was serially,is there any way to make every request handled parallelly?

**Comment by elazarl** [comment]
Did you find a solution to your problem?

Not sure I understand it.

**Comment by leafyongzhong** [comment]
I think not,I want to implement something like 

```
proxy := goproxy.NewProxyHttpServer()
proxy.OnRequest().HandleConnect(goproxy.AlwaysMitm)
proxy.OnRequest().DoFunc(func(req *http.Request, ctx *goproxy.ProxyCtx) (*http.Request, *http.Response) {
    proxy := GetSomeProxy()

    r.RequestURI = ""
    tr := &http.Transport{
        Proxy:           http.ProxyURL(proxy),
        TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
    }

    client := &http.Client{Transport: tr}
    resp, err := client.Do(r)
    if err != nil {
        log.Errorf("proxy error for URL:%v using proxy:%v . %v", r.URL, proxy, err)
        return r, nil
    }
    return nil, resp
})
log.Fatal(http.ListenAndServe(*addr, proxy))
```
to add another proxy on every request , but got some concurrency problem like response timeout or wait timeout for headers

**Comment by leafyongzhong** [comment]
@elazarl hi,wonder have you saw my comment and can still give me some advice?

**Comment by elazarl** [comment]
Can you pleases explain what are you trying to achieve?

**Comment by leafyongzhong** [comment]
@elazarl I want to implement an Unified Proxy Service(as UPS),which proxy all requests and load some random proxies to add on every request.Then the client grograms just need to set the UPS as proxy once for all
