### ISSUE TITLE
what's `NonproxyHandler` mean? 

### ISSUE THREAD

**Issue by luweimy** [elazarl/goproxy#258]
```
proxy := goproxy.NewProxyHttpServer()
proxy.Verbose = *verbose
log.Fatal(http.ListenAndServe(*addr, proxy))
```
`NonproxyHandler` is must? 
example without set `NonproxyHandler` is right?  Response `This is a proxy server. Does not respond to non-proxy requests.`
I do not understand what this name means

**Comment by elazarl** [comment]
Non proxy handler handles requests sent directly to the proxy server as if
it's a regular http server.
What would happen if you enter the url of the proxy server directly in your
browser.

**Comment by luweimy** [comment]
@elazarl 
But example without set NonproxyHandler, Response `This is a proxy server. Does not respond to non-proxy requests.`?

**Comment by elazarl** [comment]
Correct, proxy should respond only you proxy requests.

**Comment by luweimy** [comment]
thank you very much.
