### ISSUE TITLE
why `copyHeaders` remove dst header key-values first?

### ISSUE THREAD

**Issue by luweimy** [elazarl/goproxy#259]
```
func copyHeaders(dst, src http.Header) {
	for k, _ := range dst {
		dst.Del(k)
	}
	for k, vs := range src {
		for _, v := range vs {
			dst.Add(k, v)
		}
	}
}
```
I write cookie to response in middleware, but goproxy will remove response headers. What should I do?.

**Comment by elazarl** [comment]
because one header could have multiple values.

Just calling Add would keep the previous value, and add another value to
the header.
