### ISSUE TITLE
Static target URL

### ISSUE THREAD

**Issue by oliverjanik** [elazarl/goproxy#261]
Can go proxy be configured to proxy a provided url?

E.g. I hit goproxy at http://localhost:8080/cook-me-dinner and it will proxy this request to targetURL+/cook-me-dinner ?

In other words I want to hit goproxy http listener directly not as a proxy and have it resend my requests to configured URL.

**Comment by elazarl** [comment]
See nonproxyhandler

**Comment by ErikPelli** [comment]
nonproxyhandler is great for this case
