### ISSUE TITLE
How to access the `req.FormValue` when using `OnResponse().DoFunc`

### ISSUE THREAD

**Issue by sundy-li** [elazarl/goproxy#262]
When I use  `OnResponse().DoFunc`, I just found the `req.FormValue` can't access any form data, is this a bug?

     responseHandleFunc := func(resp *http.Response, ctx *goproxy.ProxyCtx) *http.Response {
		if resp == nil {
			return resp
		}
		if ctx.Req.URL.Path == some_path {
			 fmt.Println( "roomID -->",  req.Form.Get("roomID") )
		}  
		return resp
	}
	s.proxy.OnResponse().DoFunc(responseHandleFunc)

**Comment by elazarl** [comment]
Isn't that a Go issue? You need to call some parsing function beforehands?

**Comment by sundy-li** [comment]
Not yet, the Go  source code will check if has parsed.

**Comment by sundy-li** [comment]
The go ` req.FormValue `  method will call parse ,  Though I call `ParseForm`, it is still empty.
```
req.ParseForm()
log.Println("form.get", req.Form.Get("roomID"), "url query", req.URL.Query().Get("roomID"), "form value", req.FormValue("roomID"))

```

**Comment by sundy-li** [comment]
Hi, I just use two minimal codes to test this issue.
 
  code1 without pure http server (https://play.golang.org/p/svngCvdOb18)
 test script is ```curl -XPOST "http://localhost:8000/langdetect" -d 'query=abc'```
  

code2 with goproxy  (https://play.golang.org/p/kd7lSZFpTeG)
test script is ``` http_proxy=localhost:8998  curl -XPOST "http://fanyi.baidu.com/langdetect" -d 'query=abc'```

It proves that goproxy cannot access the real FormValue, may be you could look at it.

**Comment by sundy-li** [comment]
It's my error, because the request has been read, so the FormValue will get empty
