### ISSUE TITLE
is it possible to catch/handle CONNECT error without MITM?

### ISSUE THREAD

**Issue by ifuyivara** [elazarl/goproxy#267]
Without using MITM will it be possible to handle a CONNECT error (either because the host is incorrect, a time out, etc)? Everything I've tried suggest using MITM to inspect the response. I don't need/want to inspect request/responses and only take action if a connection to the host can not be established.

Thanks!

**Comment by elazarl** [comment]
Hmm... I think I had such request.
This need to be addressed.
I don't have time now, but would be happy for a PR

**Comment by ErikPelli** [comment]
The connect custom error handling has been merged in master.
Closing this issue.
