### ISSUE TITLE
Connections that are not instances on net.TCPConn are not closed properly

### ISSUE THREAD

**Issue by jasonzimmerman** [elazarl/goproxy#270]
When using a Dialer that does not return net.Conn or net.TCPConn, connections are not closed properly when making an HTTP CONNECT request. This seems to stem from [https.go:113](https://github.com/elazarl/goproxy/blob/master/https.go#L113). It seems like the code is waiting for both connections to be closed before closing both connections.

**Comment by ErikPelli** [comment]
Currently, in this case, a normal close is used, thanks to https://github.com/elazarl/goproxy/pull/585. Closing this issue.
