### ISSUE TITLE
Why req.URL.Path is always empty?

### ISSUE THREAD

**Issue by Glavic** [elazarl/goproxy#272]
Hello.
Why is `req.URL.Path` always empty? Even if URL Path is not empty?

Full example: https://gist.github.com/Glavic/54492ab4950421980bbc74bac88cefe3

Before line: 
https://github.com/elazarl/goproxy/blob/a96fa3a318260eab29abaf32f7128c9eb07fb073/dispatcher.go#L115

Add: `fmt.Printf("URL MATCH: %#v\n", req.URL)`

For example visit: `https://example.com/a/b/c?a=b`

Result is:

    URL MATCH: &url.URL{Scheme:"", Opaque:"", User:(*url.Userinfo)(nil), Host:"example.com:443", Path:"", RawPath:"", ForceQuery:false, RawQuery:"", Fragment:""}

    URL MATCH: &url.URL{Scheme:"https", Opaque:"", User:(*url.Userinfo)(nil), Host:"example.com:443", Path:"/a/b/c", RawPath:"", ForceQuery:false, RawQuery:"", Fragment:""}

Where you can see that `Path` is not set when `proxy.OnRequest(condition).HandleConnect()` is called; and `Path` is set when `proxy.OnRequest(condition).DoFunc()` is called.

Why?
Tnx

**Comment by Glavic** [comment]
@elazarl: I know you are busy wit other projects, but can you at least show me some hint or something, so I can fix this issue? Tnx

**Comment by ErikPelli** [comment]
As already explained in the readme, a CONNECT request doesn't contain the path. Another user already well explained it in this issue. Closing,
