### ISSUE TITLE
Release Binary for Linux 32 Bit

### ISSUE THREAD

**Issue by surereddy** [elazarl/goproxy#275]
Hello sir can you please give me Binary for linux 32 bit when i'm trying to build i get errors.Can you give  binary please.

--- FAIL: TestNoProxyHeaders (0.00s)
	proxy_test.go:535: Got Connection header from goproxy map[User-Agent:[Go-http-client/1.1] Connection:[close] Accept-Encoding:[gzip]]
--- FAIL: TestNoProxyHeadersHttps (0.20s)
	proxy_test.go:535: Got Connection header from goproxy map[User-Agent:[Go-http-client/1.1] Connection:[close] Accept-Encoding:[gzip]]
parse 127.0.0.1:50619: first path segment in URL cannot contain colon:-NewRequest
exit status 255
FAIL	_/root/goproxy	2.019s

**Comment by ErikPelli** [comment]
This is a library to create a custom proxy. It's not an executable like nginx that you can directly use.
You can compile one of the examples, if you need to.
