### ISSUE TITLE
No  tag or branch v1

### ISSUE THREAD

**Issue by olehbozhok** [elazarl/goproxy#276]
On the http://labix.org/gopkg.in
said 
`The following selectors would be resolved as indicated:

pkg.v1 → tag or branch v1
pkg.v2 → tag or branch v2.1.2
pkg.v3 → tag or branch v3.0`
so when I use 
vgo build 
it throw it 
`vgo: resolving import "gopkg.in/elazarl/goproxy.v1"
vgo: import "github.com/user/repo" ->
	import "gopkg.in/elazarl/goproxy.v1": unexpected status (https://api.github.com/repos/elazarl/goproxy/commits?sha=v1&until=2018-03-01T21%3A08%3A45Z&per_page=2): 404 Not Found`

could you create correct tag name for 
gopkg.in/elazarl/goproxy.v1

**Comment by ErikPelli** [comment]
We don't use gopkg.in anymore, use directly the `github.com/elazarl/goproxy` package
