### ISSUE TITLE
UDP support

### ISSUE THREAD

**Issue by ByungjinJun** [elazarl/goproxy#277]
HI, 

Thank you for your effort for goproxy.

I am implementing a proxy for both TCP and UDP/QUIC connection, but I found goproxy is only working for TCP. Do you have any plan to support UDP/QUIC? I you won't, please give me some clues about the codework I need to modify to build my own proxy based on yours.

Thanks!

**Comment by elazarl** [comment]
Thought of using something like https://github.com/lucas-clemente/quic-go ?

**Comment by ByungjinJun** [comment]
Sorry for late response. I actually implemented goproxy on top of quic-go. Quic-go doesn't support proxy. It was easy to simple integration for tcp proxy on quic-go, but I had no luck for quic proxy. I am kinda trying to develop my own version.
