### ISSUE TITLE
Issue with sessionId counter in logs

### ISSUE THREAD

**Issue by rbutola** [elazarl/goproxy#278]
While logging messages, goproxy uses SessionId to co-relate Request to Responses. 
SessionId is int64. However while printing the logs following logic is used:
ctx.Session & 0xFF
Due to this any sessionId greater than 255 would be mis-printed. 
https://github.com/elazarl/goproxy/blob/master/ctx.go
Line:44

**Comment by bharatnc** [comment]
Unless we are trying to limit the sessionId counter to count to a maximum of 255, I have no idea of why the count is and with 0XFF. Can ``0XFF`` be just removed or increased to an alternative upper limit of value?

**Comment by elazarl** [comment]
The reason is, keeping the log short, and I didn't expect more than 255
sessions at the same time.

That might be a bad decision.

**Comment by bharatnc** [comment]
I believe that making the number for sessionId counter user-configurable would make sense. Ideally,  I see that making this number to be fixed but configurable makes a lot of sense. We could allow the user to set the limit using a environment variable and leave the default to be 255. If you think that this would be fine, I can go ahead and work on that and create a pull request. Definitely let me know.

**Comment by ErikPelli** [comment]
The mask has been changed to `0xFFFF`, so now it distinguishes between something like 16k concurrent requests in the logs
