### ISSUE TITLE
How do I use different certificates for different sites at the same port

### ISSUE THREAD

**Issue by milkfr** [elazarl/goproxy#288]
example
site1: https://www.aaa.com, have CA pinning
site2: https://www.bbb.com, have CA2 pinning
they have different ca
I want proxy through a same port, and the different site flow through will use different CA, i have their CAs

**Comment by ErikPelli** [comment]
You can iimplement it into your `CertStorage` implementation saved in the proxy.
It will receive the host, and you can generate the certificate accordingly.
