### ISSUE TITLE
Go1.11 crypto changes in RSA key generation will break TestCounterEncStreamHistogram 

### ISSUE THREAD

**Issue by cybrcodr** [elazarl/goproxy#297]
The following Go 1.11 CL will break TestCounterEncStreamHistogram.
https://golang.org/cl/64451 crypto: randomly read an extra byte of randomness in some places

Per CL description ...
"""
Code has ended up depending on things like RSA's key generation being
deterministic given a fixed random Reader. This was never guaranteed and
would prevent us from ever changing anything about it.

This change makes certain calls randomly (based on the internal
fastrand) read an extra byte from the random Reader. This helps to
ensure that code does not depend on internal details.
"""

The test is depending on RSA's key generation being deterministic given a fixed random Reader. This needs to be fixed for Go1.11.

$ go version
go version go1.11beta1 darwin/amd64

$ go test -count=10 -run=TestCounterEncStreamHistogram github.com/elazarl/goproxy
--- FAIL: TestCounterEncStreamHistogram (0.00s)
    counterecryptor_test.go:95: ref:19.004849742249746 - act:21.170827134730175 = 2.1659773924804284
    counterecryptor_test.go:97: stddev of ref histogram different than regular PRNG: 19.004849742249746 21.170827134730175
--- FAIL: TestCounterEncStreamHistogram (0.00s)
    counterecryptor_test.go:95: ref:20.790646464026963 - act:19.32792351627511 = 1.4627229477518533
    counterecryptor_test.go:97: stddev of ref histogram different than regular PRNG: 20.790646464026963 19.32792351627511
--- FAIL: TestCounterEncStreamHistogram (0.00s)
    counterecryptor_test.go:95: ref:19.45895630274545 - act:21.170827134730175 = 1.7118708319847258
    counterecryptor_test.go:97: stddev of ref histogram different than regular PRNG: 19.45895630274545 21.170827134730175
--- FAIL: TestCounterEncStreamHistogram (0.00s)
    counterecryptor_test.go:95: ref:18.374534808037037 - act:21.170827134730175 = 2.7962923266931377
    counterecryptor_test.go:97: stddev of ref histogram different than regular PRNG: 18.374534808037037 21.170827134730175
--- FAIL: TestCounterEncStreamHistogram (0.00s)
    counterecryptor_test.go:95: ref:19.610121436265967 - act:21.170827134730175 = 1.5607056984642078
    counterecryptor_test.go:97: stddev of ref histogram different than regular PRNG: 19.610121436265967 21.170827134730175
FAIL
FAIL    github.com/elazarl/goproxy      0.060s

**Comment by johnerikhalse** [comment]
Is there a particular reason for not using [rand.Reader](https://golang.org/pkg/crypto/rand/) from the crypto package instead of the implementation in [counterecryptor.go](https://github.com/elazarl/goproxy/blob/master/counterecryptor.go)?

**Comment by elazar-lb** [comment]
@johnerikhalse the reason is, to have deterministic generation of certificates given a certain root certificate.

I understand the issue, and maybe we should take a different approach here.

I'd be happy for ideas.

**Comment by johnerikhalse** [comment]
@elazar-lb Maybe I'm missing something, but I didn't think that was important since it is the root certificate the client should trust.

**Comment by elazar-lb** [comment]
@johnerikhalse I recall I've had issues with that. Maybe you have to increment a version field in order for the browser to trust it, and without incrementing this field the cached previous certificate will collide with the current one?

If that's working fine for modern browsers, I've no problem with it.

**Comment by johnerikhalse** [comment]
Is this related to #314? A new certificate must have a unique serial number.

**Comment by jeffwidman** [comment]
Is this still valid? `go` `1.11` is quite old and there haven't been many new reports of problems here...

**Comment by ErikPelli** [comment]
Currently we use a random serial number for each generation, closing this issue
