### ISSUE TITLE
How to reject requests carrying a body size more than 10MB or process them transparently?

### ISSUE THREAD

**Issue by illenialx** [elazarl/goproxy#299]
I am using `goproxy` as a local proxy server that proxies requests against a remote proxy which is also `goproxy` using `Tr` member of the struct and set proxy with `Tr.Proxy`.

However I would like to `RoundTrip` the requests inbound to local proxy with a body size more than `10 MB` without using the proxy set in `Tr.Proxy`. But `ctx.RoundTrip` uses the shared `Tr` and I can't set custom proxy or disable it and process it transparently. It will always use the common proxy.

Is there a workaround for this? If I mutated it in `OnRequest().DoFunc()`'s callback, would it be concurrency safe?

**Comment by illenialx** [comment]
Solved in #300.

**Comment by elazarl** [comment]
You can look at the content of the upload, or at the headers.

I guess it depends on how you define "normal requests".

You should probably look into WAF, to find out common ways to identify
suspicious requests. Google OWASP + WAF.
