### ISSUE TITLE
DstHostIs returns with port

### ISSUE THREAD

**Issue by berkant** [elazarl/goproxy#301]
The example in readme.md won't work. It returns with the port regardless it is http or https.

**Comment by elazarl** [comment]
Hi,
Thanks for reporting it.

Care to send a PR?

Unfortunately I don't have time to fix it now.

**Comment by illenialx** [comment]
@elazarl I think that DstHostIs should not return a port. What do you think about it?

**Comment by elazarl** [comment]
Sounds like a bug. It probably should be the host with the port.
Do send a PR.
