### ISSUE TITLE
Possible to use with go-httpstat?

### ISSUE THREAD

**Issue by damien-roche** [elazarl/goproxy#304]
I am attempting to use goproxy with the following lib: https://github.com/tcnksm/go-httpstat

I currently trace requests doing something like this:

```
		var result httpstat.Result

		octx := httpstat.WithHTTPStat(req.Context(), &result)
		req = req.WithContext(octx)

		var client = &http.Client{
			Transport: &http.Transport{
				MaxIdleConnsPerHost: 0,
				DisableKeepAlives: true,
			},
			Timeout: time.Millisecond * 10000,
		}

		res, err := client.Do(req)
```

I noticed in the documentation I can set request headers, but not sure if/how I have such control over the request as above. 

I have attempted to use `proxy.OnRequest().DoFunc()` and am returning in that function my req/res (from docs if I return response then request will be ignored), but have received an error "invalid Read on closed Body". 

Appreciate any pointers.

**Comment by elazarl** [comment]
Hi,
I apologize, but I don't have time to look at it currently.

I hope someone else would be able to answer.

**Comment by damien-roche** [comment]
No probs.

I've moved away from go-httpstat to simply wrap the net/http and use net/http/httptrace directly.

My intention above was to perform a request using the proxy server and return metrics in the headers of the response.

**Comment by ErikPelli** [comment]
Goproxy is a normal http handler so it can be integrated in a go net/http Server, and it can support any compatble library
