### ISSUE TITLE
zapproxy/burp possible?

### ISSUE THREAD

**Issue by r3k2** [elazarl/goproxy#305]
Hello will it be possible for me to add extended functionality to act in basic ways as zap proxy or Burp? I am looking for libraries to create a interceptor proxy where a penetration tester could intercept the GET/POST verbs with full headers before it gets to the remote server, modify it or inspect them,  the return before it hits a browser also inspecting what is return back from the server. Thanks

**Comment by ReK2Fernandez** [comment]
bump

**Comment by ErikPelli** [comment]
https://github.com/elazarl/goproxy/pull/607 adds the functionality to keep the original header names, without canonicalization.
If you are interested about the header ordering, currently it's not possible with this library.
Feel free to fork it or propose changes with new issues about specific features and the related pull requests.
