### ISSUE TITLE
HTTP in cascadeproxy example returns Proxy Authentication Required

### ISSUE THREAD

**Issue by gbraad** [elazarl/goproxy#306]
When setting

https://github.com/elazarl/goproxy/blob/947c36da3153ff334e74d9d980de341d25f358ba/examples/cascadeproxy/main.go#L85

as

```diff
-	request, err := http.NewRequest("GET", "https://ip.cn", nil)
+	request, err := http.NewRequest("GET", "http://ip.cn", nil)
```

execution results in

```
$ ./main
2018/08/10 05:37:35 serving end proxy server at localhost:8082
2018/08/10 05:37:35 serving middle proxy server at localhost:8081
2018/08/10 05:37:36 [001] INFO: Got request / ip.cn GET http://ip.cn/
2018/08/10 05:37:36 [001] INFO: Sending request GET http://ip.cn/
2018/08/10 05:37:36 [001] INFO: Got request / ip.cn GET http://ip.cn/
2018/08/10 05:37:36 [001] INFO: Copying response to client  [407]
2018/08/10 05:37:36 [001] INFO: Copied 33 bytes to client error=<nil>
2018/08/10 05:37:36 [001] INFO: Received response 407 Proxy Authentication Required
2018/08/10 05:37:36 [001] INFO: Copying response to client 407 Proxy Authentication Required [407]
2018/08/10 05:37:36 [001] INFO: Copied 33 bytes to client error=<nil>
2018/08/10 05:37:36 status 407, data 407 Proxy Authentication Required
```

While the headers are set in `middleproxy` using:

https://github.com/elazarl/goproxy/blob/947c36da3153ff334e74d9d980de341d25f358ba/examples/cascadeproxy/main.go#L74-L77

https://github.com/elazarl/goproxy/blob/947c36da3153ff334e74d9d980de341d25f358ba/examples/cascadeproxy/main.go#L22-L24

they do not seem to arrive at the `endproxy`.

**Comment by gbraad** [comment]
@liudanking WDYT?

**Comment by liudanking** [comment]
I will check it asap

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
收件人: Gerard Braad <notifications@github.com>
发送时间: 星期五, 八月 10, 2018 13:45
收件人: elazarl/goproxy
抄送: Danieliu; Mention
主题: Re: [elazarl/goproxy] HTTP in cascadeproxy example returns Proxy Authentication Required (#306)


@liudanking<https://github.com/liudanking> WDYT?

―

**Comment by liudanking** [comment]
Hi @gbraad, the reason is that the middle proxy removes the auth header:

https://github.com/elazarl/goproxy/blob/master/proxy.go#L88

add @elazarl

**Comment by gbraad** [comment]
This should be configurable, as it is not always wanted to remove headers... especially in this case it should be passed on.

**Comment by azak-azkaran** [comment]
This is still not fixed and could be fixed with @gbraad proposed changes.
