### ISSUE TITLE
Customizing dialing in HTTPS proxy

### ISSUE THREAD

**Issue by ebroder** [elazarl/goproxy#32]
I'm more than happy to put a PR together, but wanted to get a sense of your thoughts before I wrote it up.

It's possible to override how dialing works for HTTP proxies by setting `proxy.Tr.Dial`. This is useful for e.g. setting custom connect timeouts.

There's no equivalent functionality for https proxying, because it just calls `net.Dial` directly, and I've run into clients that don't set a timeout while waiting for the 200 from the CONNECT method (Ruby's Net::HTTP has this problem)

Does it make sense to look at `Tr.Dial` from the https code? Do you have any thoughts on alternative ways to allow overriding the dialer behavior?

**Comment by OzdemirEmrah** [comment]
Hey,

What about it? We have to set Tr.Dial for each protocol. (HTTP/HTTPS).

This issue has been closed in 2014, and It's been 5 years ago. If you can solve this, we would like to use your library for our use case.

Thanks.
