### ISSUE TITLE
How to keep body send to host after I used req.ParseForm()

### ISSUE THREAD

**Issue by wejoy** [elazarl/goproxy#326]
Hi, I am new on Go and goproxy.

In my application, I need to read Form data from the request, but after I did something like that:

```
func (server *Server) Handle(r *http.Request, ctx *goproxy.ProxyCtx) (*http.Request, *http.Response) {
  ...
  r.ParseForm()
  ...
  return r, nil
}
```

The host cannot get body anymore, it just tell me something like:
`net/http: HTTP/1.x transport connection broken: http: ContentLength=75 with Body length 0`

because of the body has been readed by proxy application.

How to solve this problem? I am new on Golang, sorry if this question maybe too stupid.

**Comment by dmjones** [comment]
See https://stackoverflow.com/questions/46948050/how-to-read-response-body-twice-in-golang-middleware.

**Comment by wejoy** [comment]
> 
> 
> See https://stackoverflow.com/questions/46948050/how-to-read-response-body-twice-in-golang-middleware.

Thanks, that is really helpful!
