### ISSUE TITLE
Can not make Multiple HandleConnect(...) work simultaneously

### ISSUE THREAD

**Issue by moooofly** [elazarl/goproxy#328]
Hello, @elazarl 

In my demo, I want to do some analysis with HTTP header, so I set this after basic auth

```
proxy.OnRequest().HandleConnect(auth.BasicConnect(realm, s.Verify))
proxy.OnRequest().HandleConnect(MyHTTPHeaderAnalysis())
```

But I find that only basic auth work well.

If I comment out the line of basic auth code, my MyHTTPHeaderAnalysis() function can work normally.

So, how should I do use HandleConnect for the purpose as above?

Thanks in advance.

**Comment by moooofly** [comment]
From my test, I think there is only one `HttpsHandler` working one time.

**Comment by elazarl** [comment]
They, by design, act one after the other.
Why do you need them to act in parallel?

**Comment by moooofly** [comment]
Sorry for late response.

It is my bad to describe this issue, what I really want is just what you are saying above.

And I find the root cause. I should make the `goproxy.HttpsHandler` return correctly.

thanks again. @elazarl
