### ISSUE TITLE
HTTPS MITM example?

### ISSUE THREAD

**Issue by AnalogJ** [elazarl/goproxy#334]
Hey,

I've taken a look at the examples directory already, but I cant seem to find something that does what I want.

Basically I'm looking for how to do HTTP & HTTPS MITM request logging, similar to Fiddler. 

Can someone point me in the right direction?

**Comment by odg0318** [comment]
I think that you can use the following example to do request logging.

https://github.com/elazarl/goproxy/tree/master/examples/goproxy-customca

```golang
proxy := goproxy.NewProxyHttpServer()
proxy.OnRequest().HandleConnect(goproxy.AlwaysMitm)
proxy.OnRequest().DoFunc(OnRequest))
func OnRequest(req *http.Request, ctx *goproxy.ProxyCtx) (*http.Request, *http.Response) {
     // TODO: do logging using req variable
     return req, nil
}
```

**Comment by elazarl** [comment]
Did you get a response? If not please reopen and explain how can we further help.

**Comment by zoli** [comment]
Using `proxy.OnRequest().HandleConnect(goproxy.AlwaysMitm)` causes failiure on HTTPS requests.

Is this expected behavior?

**Comment by postace** [comment]
> Using `proxy.OnRequest().HandleConnect(goproxy.AlwaysMitm)` causes failiure on HTTPS requests.
> 
> Is this expected behavior?

Did you check the error log?
