### ISSUE TITLE
Getting warning with ipv6 connections

### ISSUE THREAD

**Issue by elgatito** [elazarl/goproxy#336]
Hello. 

I'm using proxy for proxying all the requests.
Users reporting of getting these errors:
```
WARN: Cannot read TLS response from mitm'd server dial tcp: address 2606:4700:30::681f:1003:443: too many colons in address
```

I'm not sure what is the reason and how to deal with it. 
Maybe you can help?
Thanks

**Comment by elazar-lb** [comment]
Looks like a bug in ipv6 parsing. Can you help with recreating it?

**Comment by ErikPelli** [comment]
https://github.com/elazarl/goproxy/issues/562
