### ISSUE TITLE
Sporadic remote error: tls: bad certificate

### ISSUE THREAD

**Issue by varung** [elazarl/goproxy#342]
I'm using the goproxy-customca example, with my own generate certificate. I added this certificate to firefox.  I reload https://example.com, and usually it works well, but sometimes I get errors.

For some subset of requests, I'll see an error output by the proxy:

2019/05/17 18:06:06 https://example.com:443/
2019/05/17 18:06:08 https://example.com:443/
2019/05/17 18:08:01 https://example.com:443/
2019/05/17 18:08:02 https://example.com:443/
2019/05/17 18:08:03 [022] WARN: Cannot handshake client example.com:443 remote error: tls: bad certificate

And a corresponding Firefox error:
Secure Connection Failed

An error occurred during a connection to example.com. You have received an invalid certificate. Please contact the server administrator or email correspondent and give them the following information: Your certificate contains the same serial number as another certificate issued by the certificate authority. Please get a new certificate containing a unique serial number. Error code: SEC_ERROR_REUSED_ISSUER_AND_SERIAL

**Comment by richp10** [comment]
See #341 - solution provided there..
