### ISSUE TITLE
How to use this for caching?

### ISSUE THREAD

**Issue by varung** [elazarl/goproxy#343]
Assuming I've configured the browser to use the proxy, with my own issuer certificate, which the browser will trust, I want to be able to respond to requests with my own version, rather than the remote. On the initial run I want to simply save a copy of everything that is requested, and on a later run, I want to substitute these saved copies rather than hitting the remote server.

Is this doable?

**Comment by elazar-lb** [comment]
Just keep the content in memory, and write that when the request arrives.
