### ISSUE TITLE
How to make request through socks5?

### ISSUE THREAD

**Issue by hoclamgiauus** [elazarl/goproxy#358]
I want to do like this but can't make it work. Hope anyone can give me a hint:
client -> goproxy -> socks5 -> real web server

**Comment by elazarl** [comment]
You should configure the HTTP client to use SOCKS5

**Comment by ErikPelli** [comment]
https://github.com/elazarl/goproxy/pull/573 added an example about SOCKS proxy chaining. Closing this issue.
