### ISSUE TITLE
HandleHttps should not send 200 before calling ConnectHijack's Hijack func

### ISSUE THREAD

**Issue by riraccuia** [elazarl/goproxy#376]
*ProxyHttpServer.handleHttps() currently writes a HTTP/1.0 200 OK back to the client connection before ConnectHijack's Hijack function is invoked. 

[RFC 2817](https://tools.ietf.org/html/rfc2817#section-5.3) States: 

```
5.3 Establishing a Tunnel with CONNECT

   Any successful (2xx) response to a CONNECT request indicates that the
   proxy has established a connection to the requested host and port,
   and has switched to tunneling the current connection to that server
   connection.
```

It should be therefore up to the Hijack() method implementer to send the http 200 upon confirming that the destination (wether it was changed or not) is reachable. 

This makes it impossible to cascade the http 502 back to the client in case we wanted to abort prematurely (e.g.the target address is unavailable) #376

**Comment by riraccuia** [comment]
I created a pull request

**Comment by riraccuia** [comment]
see #377

**Comment by ErikPelli** [comment]
https://github.com/elazarl/goproxy/pull/377 fixed this
