### ISSUE TITLE
Integrate travis or other CI tools to enable code checks

### ISSUE THREAD

**Issue by hoozecn** [elazarl/goproxy#381]
It seems that the library has been broken for two times just because of compile problem this week. It's bad for a 3.7k stars project.

With a simple CI tools and github, we can avoid these kind of errors before a PR was merged.

I would like to commit a pr to enable this.

@elazarl

**Comment by elazarl** [comment]
First, I accept the criticism. I totally had to test them before merging commits, unforunately I do not have the time to invest as I did when I first started the project.

I'd love to see such a commit, and I'll definitely start testing commits from now on.

I appreciate your input!

**Comment by elazarl** [comment]
(and quite frankly, I haven't realize people actually use this library. I thought it was a niche project with at most 10 users for some specialized needs. So I'm really happy to see that)

**Comment by hoozecn** [comment]
> (and quite frankly, I haven't realize people actually use this library. I thought it was a niche project with at most 10 users for some specialized needs. So I'm really happy to see that)

Thanks for your work. It does meet our "specialized needs" LOL
