### ISSUE TITLE
goproxy.AlwaysReject seems doesn't work

### ISSUE THREAD

**Issue by hundan2020** [elazarl/goproxy#386]
**which code**

this example <https://github.com/elazarl/goproxy/blob/master/examples/goproxy-eavesdropper/main.go#L22>

**what I do**

```
curl https://test.baidu.com/ -x "http://127.0.0.1:8080" -k
```

**what I except**

connect failed

**what actually happen**

connected

![image](https://user-images.githubusercontent.com/9510938/81101506-d99f5c00-8f40-11ea-8c51-dec7220e4358.png)

**some supplement**

in line 22, we got 

```golang
proxy.OnRequest(goproxy.ReqHostMatches(regexp.MustCompile("^.*baidu.com$"))).
		HandleConnect(goproxy.AlwaysReject)
```

in the doc <https://godoc.org/github.com/elazarl/goproxy#ReqProxyConds.HandleConnect> , we find the explain **rejects all CONNECT requests**, so I think my connect should be reject, but I connected successfully, it seems doesn't work

![image](https://user-images.githubusercontent.com/9510938/81101506-d99f5c00-8f40-11ea-8c51-dec7220e4358.png)

Is that my problem?

**Comment by NXAO** [comment]
Hi @hundan2020 try using this code:
```
proxy.
		OnRequest(goproxy.ReqHostMatches(regexp.MustCompile("baidu.com"))).
		HandleConnect(goproxy.AlwaysReject)
```

**Comment by CoolSpring8** [comment]
According to package [http](https://golang.org/pkg/net/http/#Request) documentation, req.Host "may be of the form 'host:port'".

So when visiting https://test.baidu.com/, req.Host is actually "test.baidu.com:443", which doesn't match with the `regexp.MustCompile("^.*baidu.com$")` .

(One more note: the dot(".")s in the above regular expression are not escaped, so it matches "testbaidu.com" "test.baidu1com" as well. Maybe ``regexp.MustCompile(`^(.*\.)?baidu\.com$`)`` would be better?)

**Comment by adubkov** [comment]
On a same note: 
```
proxy.OnRequest(goproxy.ReqHostMatches(regexp.MustCompile("^.*$"))).HandleConnect(goproxy.AlwaysReject)
```
Doesn't seem to work. I want to block all traffic that are not explicitly allowed.
