### ISSUE TITLE
Not working with docker (linux)!

### ISSUE THREAD

**Issue by khangpropk123** [elazarl/goproxy#401]
I deploy proxy server in docker and it not working. I alway get nil as response.
"
 &{GET http://ocsp.apple.com:80/ocsp04-devid01/ME4wTKADAgEAMEUwQzBBMAkGBSsOAwIaBQAEFDOB0e%2FbaLCFIU0u76+MSmlkPCpsBBRXF+2iz9x8mKEQ4Py+hy0s8uMXVAIIA%2FQ7oX9zlg8= HTTP/1.1 1 1 map[Accept:[*/*] Accept-Language:[en-us] User-Agent:[com.apple.trustd/2.0]] {} <nil> 0 [] false ocsp.apple.com:80 map[] map[] <nil> map[] 172.19.0.1:49460  <nil> <nil> <nil> 0xc00c6198c0}
proxy_1    | 2020/08/26 07:49:08 http: panic serving 172.19.0.1:49460: runtime error: invalid memory address or nil pointer dereference
proxy_1    | goroutine 38740 [running]:
proxy_1    | net/http.(*conn).serve.func1(0xc00c6da8c0)
proxy_1    |    /usr/local/Cellar/go/1.13.4/libexec/src/net/http/server.go:1767 +0x139
proxy_1    | panic(0x7101e0, 0x9e9380)
proxy_1    |    /usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:679 +0x1b2
proxy_1    | _/Users/tuankhang/Documents/Go_Project/MyProject/workspace/src/GoProxy/core/proxy.(*ProxyCore).HandleConnect.func1(0x0, 0xc00c7542a0, 0x0)
proxy_1    |    /Users/tuankhang/Documents/Go Project/MyProject/workspace/src/GoProxy/core/proxy/type.go:63 +0xf9
proxy_1    | github.com/elazarl/goproxy.FuncRespHandler.Handle(0xc00041f4e0, 0x0, 0xc00c7542a0, 0x1)
proxy_1    |    /Users/tuankhang/Documents/Go Project/PathDemo/src/github.com/elazarl/goproxy/actions.go:35 +0x3a
proxy_1    | github.com/elazarl/goproxy.(*ProxyConds).Do.func1(0x0, 0xc00c7542a0, 0x5)
proxy_1    |    /Users/tuankhang/Documents/Go Project/PathDemo/src/github.com/elazarl/goproxy/dispatcher.go:284 +0x142
proxy_1    | github.com/elazarl/goproxy.FuncRespHandler.Handle(0xc0002e3880, 0x0, 0xc00c7542a0, 0x0)
proxy_1    |    /Users/tuankhang/Documents/Go Project/PathDemo/src/github.com/elazarl/goproxy/actions.go:35 +0x3a
proxy_1    | github.com/elazarl/goproxy.(*ProxyHttpServer).filterResponse(0xc0001efcc0, 0x0, 0xc00c7542a0, 0x7e39c0)
proxy_1    |    /Users/tuankhang/Documents/Go Project/PathDemo/src/github.com/elazarl/goproxy/proxy.go:74 +0x8d
proxy_1    | github.com/elazarl/goproxy.(*ProxyHttpServer).ServeHTTP(0xc0001efcc0, 0x7e92a0, 0xc00c541340, 0xc00c53f600)
proxy_1    |    /Users/tuankhang/Documents/Go Project/PathDemo/src/github.com/elazarl/goproxy/proxy.go:125 +0x9ea
proxy_1    | net/http.serverHandler.ServeHTTP(0xc0001a5dc0, 0x7e92a0, 0xc00c541340, 0xc00c53f600)
"
In real machine or ubuntu vmware, it's working normally.

**Comment by vaskozl** [comment]
I am also hitting this.

**Comment by ErikPelli** [comment]
Based on the stacktrace, this panic happens inside an handler managed by you and therefore is not something that depends on the library code. Closing this issue.
