### ISSUE TITLE
can't handle PRI requests to support HTTP/2 proxying

### ISSUE THREAD

**Issue by ahmetb** [elazarl/goproxy#407]
I ran the sample code intercepting requests in the README: https://github.com/elazarl/goproxy/tree/0581fc3aee2d07555835bed1a876aca196a4a511#a-taste-of-goproxy and made request to http://nghttp2.org/ which supports h2c (unencrypted http/2).

```
curl --http2 -x localhost:8080  http://nghttp2.org/
```

this responds with `curl: (16) Error in the HTTP2 framing layer`

Logs show:

```
go run ./
2020/10/08 17:32:47 [001] INFO: Got request / nghttp2.org GET http://nghttp2.org/
2020/10/08 17:32:47 [001] INFO: Sending request GET http://nghttp2.org/
2020/10/08 17:32:50 [001] INFO: Received response 101 Switching Protocols
2020/10/08 17:32:50 [001] INFO: Copying response to client 101 Switching Protocols [101]
2020/10/08 17:32:50 [001] INFO: Copied 0 bytes to client error=http: request method or response status code does not allow body
2020/10/08 17:32:50 [002] INFO: Got request *  PRI *
```

This is because the server gets the HTTP/2 preface request that has `PRI` method (see [page 10](https://tools.ietf.org/html/rfc7540#page-10) of the spec):

    PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n"

and doesn't know what to do with it. 
In this case, the proxy needs to respond to the client with a [SETTINGS frame](https://tools.ietf.org/html/rfc7540#section-6.5) (I'm not sure how to do this) signaling it supports http2.

Naturally, it comes to the handler the user writes, but I don't think users like me will know what to do with it. Ideally it would be better if goproxy just notices meta-requests like `PRI`.

Use Case: I needed this because it would be immensely useful to MITM the gRPC requests with this proxy. gRPC works over h2 and when you run it unencrypted it uses h2c. But existing tools like `mitmproxy` don't support h2c. Using goproxy, I could write my own mini-tool that does this.

**Comment by ahmetb** [comment]
This was a mistake on my side.

Apparently all you need to do is to wrap the handler from goproxy with `golang.org/x/net/http2/h2c` like this:

```go
func allowh2c(next http.Handler) http.Handler {
	h2server := &http2.Server{IdleTimeout: time.Second * 60}
	return h2c.NewHandler(next, h2server)
}
```

and it makes progress on proxying HTTP/2 requests such as grpc as well.

**Comment by fadyosman** [comment]
Hi @ahmetb,

Were you able to get this to work? I tried the allowh2c function like this.

> log.Fatal(http.ListenAndServe(":8080", allowh2c(proxy)))

However, curl gives the following error.

> curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)

And I get the following error in the proxy side.

> 2024/02/21 00:49:31 [001] INFO: Sending request GET http://nghttp2.org/
2024/02/21 00:49:32 [001] INFO: Received response 101 Switching Protocols
2024/02/21 00:49:32 [001] INFO: Copying response to client 101 Switching Protocols [101]
2024/02/21 00:49:32 [001] INFO: Copied 4096 bytes to client error=http2: stream closed

Any idea on how to fix this error?
