### ISSUE TITLE
/Mea culpa/ Bug in https.go, you treat err == "EOF" as error

### ISSUE THREAD

**Issue by stiray** [elazarl/goproxy#410]
https://github.com/elazarl/goproxy/blob/0581fc3aee2d07555835bed1a876aca196a4a511/https.go#L267

This line here has inadequate checking, should be:
``
if _, err := io.Copy(chunked, resp.Body); err != nil && "EOF" != err.Error() {
``

**Comment by onokonem** [comment]
https://golang.org/pkg/io/#Copy

_A successful Copy returns err == nil, not err == EOF. Because Copy is defined to read from src until EOF, it does not treat an EOF from Read as an error to be reported._

**Comment by stiray** [comment]
Argh, true, another beautiful goism in standard libraries, it doesnt compare error but matches pointer within copy so the only proper way of returning error from read is io.EOF.
