### ISSUE TITLE
Cascading proxy stopped working after a while

### ISSUE THREAD

**Issue by yhjhoo** [elazarl/goproxy#411]
I am encountering Cascading proxy stopped working after a while, how to do troubleshoot?

**Comment by yhjhoo** [comment]
The following java11 httpclient can cause issue to kill proxy service, got too many files opened and connection reset error. is there a way to set a max time allowed for a connection?

![image](https://user-images.githubusercontent.com/24640/97427332-512dd100-194f-11eb-8b4c-e86487506223.png)


```
@Test
    void java11() throws InterruptedException {
        for (int i = 0; i < 100_000; i++) {
            System.out.println("i = " + i);
            try {
                postYammer(i);
            } catch (IOException e) {
                e.printStackTrace();
            }
            System.out.println("Thread started i = " + i);
        }
        System.out.println("sleep");
        Thread.sleep(1_000_000_000);
    }

    private void postYammer(int sequence) throws IOException, InterruptedException {
        HttpClient client = HttpClient.newBuilder().proxy(ProxySelector.of(new InetSocketAddress("proxyHost", 8080))).build();
        HttpRequest request = HttpRequest.newBuilder().uri(URI.create("https://www.yammer.com/favicon.ico")).build();
        HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
        System.out.println(sequence + "=======" + new Date().toString() + ", statusCode: " + response.statusCode());
        Thread.sleep(300);
    }
```

**Comment by ErikPelli** [comment]
You can use any Go http standard library to limit the time of a request, since GoProxy is a normal standard library compatible handler.
If you decide to use go chi, for example, there is the Timeout middleware available: https://github.com/go-chi/chi/blob/master/middleware/timeout.go
