### ISSUE TITLE
How can I completely close the log information

### ISSUE THREAD

**Issue by Threezh1** [elazarl/goproxy#422]
Hello, I want to close all warning messages like the following, what should I do?
I have tried `proxy.Verbose = false`, but this does not completely turn them off.

![image](https://user-images.githubusercontent.com/45116144/104726900-67d60e00-576f-11eb-9bdf-9e382f703b1b.png)

**Comment by CoolSpring8** [comment]
Since all log messages are written via a custom logger, adding this should do the trick:
`proxy.Logger = log.New(ioutil.Discard, "", 0)`

**Comment by Threezh1** [comment]
> Since all log messages are written via a customizable logger (in ctx.go), this should just do the trick:
> `proxy.Logger = log.New(ioutil.Discard, "", 0)`

Thank you very much
