### ISSUE TITLE
Does not appear to work at all

### ISSUE THREAD

**Issue by mcfearsome** [elazarl/goproxy#426]
The following code snippet does not produce any output, proxy behavior is working just fine, DoFunc just never gets called.

```
❯ go version
go version go1.16beta1 darwin/arm64
```

```
# p.server is created with goproxy.NewProxyHttpServer()
p.server.OnResponse().DoFunc(func(resp *http.Response, ctx *goproxy.ProxyCtx) *http.Response {
	log.Println("OnResponse")
	log.Println(resp.Request.Host)
	log.Printf("%+v\n", resp.Request)
	os.Exit(1)
	return resp
})
```

The following produces some output, but the proxy behavior breaks, as in I can't browse anymore:
```
	var handler goproxy.FuncHttpsHandler = func(host string, ctx *goproxy.ProxyCtx) (*goproxy.ConnectAction, string) {
		log.Println("HandleConnect")
		log.Printf("Host: %s\n", host)

		return goproxy.OkConnect, ""
	}
	p.server.OnRequest().HandleConnect(handler)
```

**Comment by iIIusi0n** [comment]
I'm going through the same thing...

**Comment by CoolSpring8** [comment]
By default only `http` traffic is handled by these OnRequest/OnResponse handlers, while `https` traffic will pass through untouched.
Depending on what you like to do on https connections, you might want something like [`AlwaysMitm`](https://pkg.go.dev/github.com/elazarl/goproxy#AlwaysMitm) or [`AlwaysReject`](https://pkg.go.dev/github.com/elazarl/goproxy#AlwaysReject).

So to explain why the snippets doesn't work:

- In the first snippet, the proxy server is not yet configured to act on a https connection as described above. Therefore, hen visiting a site with https, the handler function is never called; If you visit a site without https, the information is expected to be logged.

- In the second snippet, the `var handler goproxy.FuncHttpsHandler` you defined returns an empty string as the `host`, which is invalid for a [`CONNECT`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT) request, and that prevents the normal browsing.

(There are some examples available for reference in the [`examples`](https://github.com/elazarl/goproxy/tree/master/examples) directory and I would suggest checking out some of them.)

**Comment by JanneKiiskila** [comment]
Should this issue closed, if the answer suffices @mcfearsome ?
