### ISSUE TITLE
High CPU Usage with MITM certificates

### ISSUE THREAD

**Issue by aakarim** [elazarl/goproxy#430]
It seems like ~70% of my CPU time is being used by MITM negotiating TLS certificates. Here's a flame graph that shows that goProxy.signHost is being called.
![image](https://user-images.githubusercontent.com/3791557/111051776-85f97b00-844d-11eb-80b8-8d2956669954.png)

![image](https://user-images.githubusercontent.com/3791557/111051837-e092d700-844d-11eb-9e7c-aec999d3e5b9.png)

Are there any caching strategies that can make this less CPU intensive?

**Comment by aakarim** [comment]
After some searching I found this undocumented part of the api from this PR https://github.com/elazarl/goproxy/pull/332

Here is a dead simple version of this cert store that works well for me. In my case I only connect to a very small number of domains, but If you have a high number of certificates you need to manage it might be best to use something like Ristretto https://github.com/dgraph-io/ristretto to manage a fixed in-memory cache with TTL.

```
package service

import (
	"crypto/tls"
	"sync"
)

type CertStorage struct {
	certs sync.Map
}

func (tcs *CertStorage) Fetch(hostname string, gen func() (*tls.Certificate, error)) (*tls.Certificate, error) {
	var cert tls.Certificate
	icert, ok := tcs.certs.Load(hostname)
	if ok {
		cert = icert.(tls.Certificate)
	} else {
		certp, err := gen()
		if err != nil {
			return nil, err
		}
		// store as concrete implementation
		cert = *certp
		tcs.certs.Store(hostname, cert)
	}
	return &cert, nil
}

func NewCertStorage() *CertStorage {
	tcs := &CertStorage{}
	tcs.certs = sync.Map{}

	return tcs
}


```

**Comment by hamza02x** [comment]
Hey!

Can you please provide full the example? I have been facing the same.

**Comment by rajprithiv88** [comment]
Do we have a solution for this?
