### ISSUE TITLE
Custom CA will not Work

### ISSUE THREAD

**Issue by ajcypherint** [elazarl/goproxy#449]
Since the GoproxyCa is a global variable it adds it self to the tlsConfig.Certificates it will break a custom MITM  CA.
This part of the code loads the hard coded cert and breaks custom CA.

[initial load of global](https://github.com/elazarl/goproxy/blob/a92cc753f88eb1d5f3ca49bd91da71fe815537ca/https.go#L32)

All new Custom CA are then Appended to the .Certificates instead of replacing .Certificate array element 0.
[append](https://github.com/elazarl/goproxy/blob/8e322dfb79c43cc078201ade94238d8c7191dfe7/https.go#L447)

If you want a custom CA to work define your own  `TLSConfigFromCA` that removes the first certificate
https://github.com/elazarl/goproxy/blob/8e322dfb79c43cc078201ade94238d8c7191dfe7/https.go#L447

by adding after above line
```
config.certificates=config.certificates[1:] 
```
thus removing the offending certificate
so maybe:

```
func TLSConfigFromCA(ca *tls.Certificate) func(host string, ctx *ProxyCtx) (*tls.Config, error) {
	return func(host string, ctx *ProxyCtx) (*tls.Config, error) {
		var err error
		var cert *tls.Certificate

		hostname := stripPort(host)
		config := defaultTLSConfig.Clone()
		ctx.Logf("signing for %s", stripPort(host))

		genCert := func() (*tls.Certificate, error) {
			return signHost(*ca, []string{hostname})
		}
		if ctx.certStore != nil {
			cert, err = ctx.certStore.Fetch(hostname, genCert)
		} else {
			cert, err = genCert()
		}

		if err != nil {
			ctx.Warnf("Cannot sign host certificate with provided CA: %s", err)
			return nil, err
		}

		config.Certificates = append(config.Certificates, *cert)
		config.Certificates = config.Certificates[1:]
		return config, nil
	}
}
```

**Comment by guzzijones** [comment]
delete this.

**Comment by elazarl** [comment]
@ajcypherint can't you just change `goproxy GoproxyCa` to your liking?

**Comment by ajcypherint** [comment]
Yes. Close this issue. The problem was with our internal certificate.

**Comment by Buzz2d0** [comment]
You can refer to the code I wrote, It works:
1. gen-cert: https://github.com/Buzz2d0/xssfinder/blob/main/pkg/proxy/cert/gen.go
2. set-cert: https://github.com/Buzz2d0/xssfinder/blob/main/pkg/proxy/ca.go#L21
