### ISSUE TITLE
"handleHttps" Will cause connection leaks 

### ISSUE THREAD

**Issue by lujinda** [elazarl/goproxy#451]
```Go
		if targetOK && clientOK {
			go copyAndClose(ctx, targetTCP, proxyClientTCP)
			go copyAndClose(ctx, proxyClientTCP, targetTCP)
		}
```
If the client actively closes the connection, and the remote server does not write any data, and the inactivity timeout is not configured. At this time, only the first copyAndClose will end (io.EOF occurs on the client).

**Comment by ErikPelli** [comment]
Can you open a pull request to fix this issue?

**Comment by ErikPelli** [comment]
Fixed by https://github.com/elazarl/goproxy/pull/256
