### ISSUE TITLE
Persist authentication information through handlers

### ISSUE THREAD

**Issue by farajist** [elazarl/goproxy#457]
Thanks for the amazing work,

As it is now, the auth extension discards `Proxy-Authorization` header and therefore no auth information remains when request is passed to the next handler, which can be limiting for some features like rate limiting (based on auth credentials) ...etc.

I think this has been addressed in #291, are there any plans to support the change, or implementation guidance to contribute ?

**Comment by mvanholsteijn** [comment]
I also need the ability to add a Proxy-Authorization header to an outgoing connection.

**Comment by ErikPelli** [comment]
You can parse the data yourself and persist them in the `ctx.UserData` field, no need to add other fields or merge any Pull Request
