### ISSUE TITLE
Proxy chain https requests to upstream proxy without terminating

### ISSUE THREAD

**Issue by jtweaver** [elazarl/goproxy#464]
Is it possible to chain https requests to an upstream proxy without terminating TLS? I've seen in a couple examples that chaining can be done by updating the transport in the `HandleConnectFunc`, but all examples use `MitmConnect`. I've tried without using MITM, but the request doesn't end up being sent to the upstream proxy.

```
proxy.OnRequest().HandleConnectFunc(func (host string, ctx *goproxy.ProxyCtx) (*goproxy.ConnectAction, string) {
  var proxyUrl *url.URL
  proxyUrl, _ = url.Parse("http://127.0.0.1:3128")
  proxy.Tr = &http.Transport{
    Proxy: http.ProxyURL(proxyUrl),
    TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
  }

  return goproxy.MitmConnect, host
})
```

**Comment by jtweaver** [comment]
@ciokan I used `NewConnectDialToProxyWithHandler` to connect to the upstream proxy within the HandleConnectFunc.

```
ctx.Proxy.ConnectDial = ctx.Proxy.NewConnectDialToProxyWithHandler(<proxy_addr>, func(req *http.Request) {
	logger.Info("Request complete", zap.String("logType", "canonical"))
})
```

**Comment by xzycn** [comment]
> 

This way cannot solve the concurrency problem :(
