### ISSUE TITLE
forward proxy

### ISSUE THREAD

**Issue by journeytosilius** [elazarl/goproxy#471]
hi, I need to forward a connection made to https like : 

origin request --> local proxy ---> proxy at the internet --- > final destination 

and back.

I believe this is called forward proxying, with the particularity of doing the forward to an open proxy on the internet instead of locally

I am fairly new to this so I want to ask if there is an example of forward proxy I can study ?

Thanks

**Comment by xzycn** [comment]
This should be the way you want:
https://github.com/elazarl/goproxy/tree/master/examples/cascadeproxy
> client --> middle proxy --> end proxy --> internet
