### ISSUE TITLE
Dose this repo stay semiactive？

### ISSUE THREAD

**Issue by xzycn** [elazarl/goproxy#474]
Just like title says，this repo seems to stay semiactive？
There are so many issues opened, but almost none of them to be answered in a long time :(
And docs for this repo are too few.
Anyway, thanks for your great work on this project,but we want it to better :)

**Comment by elazarl** [comment]
Thanks for the kind work,
I think I said it in the past, I don't have time now for making new PRs, but I'm happy to review PRs people open, and merged fixes a couple of times.

I apologize for not having the time to properly answer every issue, most of them requires investigation, some are answered by other people in the community, some when resolved were issues not specific to goproxy.

If anyone has time for investigating new issues, answering questions from the community - I'll be happy for any help.
