### ISSUE TITLE
example code proxy as socks5

### ISSUE THREAD

**Issue by undefinedteam1** [elazarl/goproxy#480]
hi all.
I'm very like this project, I used as http proxy very good.
But now, I need custom running as socks5 proxy and fix outgoing ip address
Anyone have example for this please give me.

many thanks

**Comment by minhdv92** [comment]
Anyone can help me?

**Comment by minhdv92** [comment]
@elazarl please help me

**Comment by minhdv92** [comment]
@elazarl its very importance for me. Please check for me. Thanks

**Comment by fjqisba** [comment]
you can try try this project，https://github.com/fjqisba/MyHoneyProxy，I can't guarantee that it's useful for you

**Comment by ErikPelli** [comment]
SOCKS proxies are outside the scope of this project.
You can have an HTTP proxy server and overwrite the request connection to use external SOCKS proxies for the request, thus making a proxy "aggregator".

**Comment by elazarl** [comment]
Maybe we should add an example in the README, as this is recurring request
