### ISSUE TITLE
HTTPS proxy hangs during stress test

### ISSUE THREAD

**Issue by sausagenoods** [elazarl/goproxy#481]
Hello, I implemented a forward HTTPS proxy using this library. When I test using [ab-proxy](https://github.com/maurice2k/ab-proxy), it always hangs during the test. Here is the relevant section of the code:
```go
func main() {
        loadConfig()
        authCache, _ = bigcache.NewBigCache(bigcache.DefaultConfig(c.credCacheTTL))
        proxy := goproxy.NewProxyHttpServer()
        proxy.Tr.MaxIdleConns = 0
        proxy.Tr.MaxConnsPerHost = 0
        proxy.Tr.MaxIdleConnsPerHost = 0
        proxy.Verbose = c.verbose
        s := &http.Server{
                Addr: c.bindAddr,
                Handler: proxy,
                TLSNextProto: make(map[string]func(*http.Server, *tls.Conn, http.Handler)),
        }
        log.Fatal(s.ListenAndServeTLS(c.certFile, c.keyFile))
}
```
Here is the command I'm using to test:
`./ab-proxy -c 20 -n 5000 --proxy 'https://user:pass@myproxyserver.domain' 'https://syd1.speedtest.telstra.net:8080/download?size=10485760'`
It makes 5000 GET requests to download 10 MiB from a server using 20 threads through the proxy server.

When I import [a fork of this library](https://github.com/stripe/goproxy/) instead without changing anything in the code, it no longer hangs and works fine.

**Comment by ErikPelli** [comment]
We have integrated all the fixes from the forks and I just run the benchmark you specified without any problem.
Can you confirm that now it works also for you, so we can close this issue?

P.S. If you plan to use the proxy MITM feature in the future, I highly recommend you to use a CertStorage implementation, so the proxy server doesn't have to regenerate the certificates for each request.

**Comment by ErikPelli** [comment]
Closing this issue because it has been resolved
