### ISSUE TITLE
how to print client IP addrs on my server?

### ISSUE THREAD

**Issue by anyanfei** [elazarl/goproxy#490]
Excuse me, how to print client IP addrs on my server?

func main() {
	flag.Usage = func() {
		flag.PrintDefaults()
	}
	flag.Parse()
	if serverPort == "" {
		log.Fatalln("Error: please setting correct server port")
	}
	endProxy := goproxy.NewProxyHttpServer()
	endProxy.Verbose = true
	auth.ProxyBasic(endProxy, "my_realm", func(user, pwd string) bool {
		return user == username && pwd == password
	})
	log.Println("serving proxy server port at", serverPort)
	http.ListenAndServe(":"+serverPort, endProxy)
	fmt.Println("The proxy server end.")
}

**Comment by ErikPelli** [comment]
You can use something like
```
proxy.OnRequest().DoFunc(
  func(r *http.Request, ctx *goproxy.ProxyCtx)(*http.Request,*http.Response) {
     fmt.Println(r.RemoteAddr)
     return r,nil
  }
)
```
