### ISSUE TITLE
Facebook and Instagram apps fail to work through GoProxy

### ISSUE THREAD

**Issue by icoris** [elazarl/goproxy#494]
Hi,

I've been using GoProxy for a while, and I've noticed that both the Facebook app and Instagram fail to work with GoProxy. 
In Facebook app, if you click on the Friend tab, it displays "Unable to connect". 

I have tested GoProxy in a basic mode by using GoProxy-Basic from the examples and but both Facebook and Instagram still don't work.

I can't see any errors generated by GoProxy, so I am a bit lost as to what the apps can't do when running through GoProxy as a proxy server.

Does anyone have any ideas?

**Comment by ErikPelli** [comment]
Yeah probably it's a SSL pinning issue, where their mobile application recognized a MITM with a different Certification Authority, and blocks everything.
You have to manually modify the app to remove this check.
