### ISSUE TITLE
Status code on unresolvable hosts.

### ISSUE THREAD

**Issue by thekvs** [elazarl/goproxy#51]
If we try to access through goproxy host which doesn't have DNS record goproxy returns 500 (Internal Server Error) HTTP status code, while squid-cache returns 502 (Bad Gateway) HTTP status code. Shouldn't goproxy simulate squid's behavior?

```
$ curl -v --proxy 127.0.0.1:3129  --url http://no.exists/
* About to connect() to proxy 127.0.0.1 port 3129 (#0)
*   Trying 127.0.0.1...
* Adding handle: conn: 0x1d71bd0
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x1d71bd0) send_pipe: 1, recv_pipe: 0
* Connected to 127.0.0.1 (127.0.0.1) port 3129 (#0)
> GET http://no.exists/ HTTP/1.1
> User-Agent: curl/7.32.0
> Host: no.exists
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< Date: Tue, 20 May 2014 13:13:02 GMT
< Content-Length: 41
< 
dial tcp: lookup no.exists: no such host
* Connection #0 to host 127.0.0.1 left intact
$ 
```

**Comment by mmatczuk** [comment]
Any update on that?
The correct behavior is to return 502 (not 503) since this is a proxy specific error code.
Service Unavailable is a "come back later" I'm busy response.

**Comment by lambrospetrou** [comment]
Is there any progress on this issue, or was it somehow addressed in a different way?

**Comment by ErikPelli** [comment]
After https://github.com/elazarl/goproxy/pull/585, the error can be handled both using the Connection handler, if it's related to it, or directly using a response handler, as suggested by @lambrospetrou
