### ISSUE TITLE
Potential Typo in Request Handling - "r.Close" misset to False?

### ISSUE THREAD

**Issue by tiaras12** [elazarl/goproxy#515]
https://github.com/elazarl/goproxy/blob/3ec07828be7ac4d84b1561216ae707dc12b2739a/proxy.go#L99-L108

It seems that req.Close should set to true when the "Connection" header contains "close" according the comment above.  
However, in the above snippet, r.Close is being set to false. Is this a typo or I misunderstanding it

**Comment by ErikPelli** [comment]
In this function r is the only variable that contains a request, so it's the one that the comment refers to.
If this r - req grammar error bothers you, you can open a pull request to fix the typo.

**Comment by ErikPelli** [comment]
req.Close is not related to this line but is an explaination of what the Go standard library does when handling the request.
This is well explained, since there is a link of the source to the go stdlib code itself.
Closing this issue.
