### ISSUE TITLE
Flagged as Virus

### ISSUE THREAD

**Issue by RPGillespie6** [elazarl/goproxy#544]
Great tool!

Just an observation that any `.exe` created with this library seems to be flagged as viruses by Google (Drive) and Microsoft (Windows Defender).

For example, if you compile this to an exe and put it in Google Drive:
```
package main

import (
    "github.com/elazarl/goproxy"
    "log"
    "net/http"
)

func main() {
    proxy := goproxy.NewProxyHttpServer()
    proxy.Verbose = true
    log.Fatal(http.ListenAndServe(":8080", proxy))
}
```

When you try to download it, you get:
![image](https://github.com/user-attachments/assets/fd437df7-9b67-484d-812b-c398d4f8ecc2)

And furthermore, Google doesn't allow you to share it with others. So only the owner can download it.

Microsoft similarly instantly quarantines it once you try to run it.

It could just be the nature of the code, but just wanted to bring up this issue in case anyone had ideas for workarounds

**Comment by elazarl** [comment]
Thanks,
Not sure how to resolve this issue.

**Comment by RPGillespie6** [comment]
We can close the issue, there's probably nothing you can do except advise people using the library to EV sign exes intended for distribution.
