### ISSUE TITLE
proxy.go:165 nil pointer dereference on empty body

### ISSUE THREAD

**Issue by QuentinN42** [elazarl/goproxy#547]
As the `http.Response` body is an interface, it may be `nil`.

https://github.com/elazarl/goproxy/blob/6741dbfc16a13e515d5f2b485eb4be24692e54de/proxy.go#L164-L167

Here we may want to add a `if resp.Body != nil` ...

**Comment by ErikPelli** [comment]
[Go documentation](https://pkg.go.dev/net/http#Response)

// Body represents the response body.
// ...
// The http Client and Transport guarantee that Body is always
// non-nil, even on responses without a body or responses with
// a zero-length body. It is the caller's responsibility to
// close Body.
