### ISSUE TITLE
Does this project currently support or plan to support SOCKS5 proxy services in the future?

### ISSUE THREAD

**Issue by MmToon** [elazarl/goproxy#552]
Does this project currently support or plan to support SOCKS5 proxy services in the future?

**Comment by elazarl** [comment]
You can do that by overriding the Connect method IIRC

**Comment by ErikPelli** [comment]
A SOCKS server is not the target of this project, which is an HTTP/HTTPS proxy library.
However, as @elazarl stated, you can overwrite the Connect behaviour with your own implementation to forward the request to external SOCKS proxy and using the HTTP proxy server as an aggregator.

**Comment by ErikPelli** [comment]
https://github.com/elazarl/goproxy/issues/558
