### ISSUE TITLE
Integrate fixes from forks

### ISSUE THREAD

**Issue by ErikPelli** [elazarl/goproxy#564]
There are various forks that added fixes/patches to the codebase, but there isn't any pull request to integrate them into this project.
We should analyze what can be integrate and add them accordingly.
Among the forks:
- ~https://github.com/stripe/goproxy~ ✅
- ~https://github.com/Windscribe/goproxy~
- ~https://github.com/abourget/goproxy~ ✅
- ~https://github.com/SpectoLabs/goproxy (we are violating RFC7230 too, as explained in this issue in another project: https://github.com/pylons/waitress/issues/165)~ ✅ 
- ~https://github.com/forensant/goproxy~ ✅ 
- ~https://github.com/elazarl/goproxy/pull/514 (to avoid adding an header to each request when not needed)~

~Replace http constant values with their HTTP equivalent.
e.g. "HEAD" -> http.MethodHead~ ✅

**Comment by elazarl** [comment]
Are you aware of usefulforks?

**Comment by ErikPelli** [comment]
In the first message I put a list of the possible forks to analyze

**Comment by ErikPelli** [comment]
I integrated the fixes from all the forks in the initial message. Closing this issue!
