### ISSUE TITLE
All Hop-By-Hop headers should be removed

### ISSUE THREAD

**Issue by KingCrunch** [elazarl/goproxy#78]
See [RFC2616](https://www.ietf.org/rfc/rfc2616.txt) 13.5.1. [`Connection`](https://github.com/elazarl/goproxy/blob/95478531e83455c0c36f72e99e1da6897cfe4996/proxy.go#L83-L89) is not the only single hop header and all should be removed.

> __Hop-by-hop headers__, which are meaningful only for a single
> transport-level connection, and __are not stored by caches or
> forwarded by proxies.__

Compare with [reverseproxy:90](https://golang.org/src/net/http/httputil/reverseproxy.go#L90)

**Comment by elazarl** [comment]
@KingCrunch please let me know if indeed this covers all headers. Have a look at the test.
