### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by zhangpy** [elazarl/goproxy#80]
When I use gopkg instead of github, the code failed to compile:

src/gopkg.in/elazarl/goproxy.v1/ext/html/html.go:14:2: cannot find package "github.com/elazarl/goproxy" in any of:
	~~~ (from $GOROOT)
	~~~/src/github.com/elazarl/goproxy (from $GOPATH)

**Comment by elazarl** [comment]
@zhangpy 

Can you help me recreate the issue.

I'm doing

```
go get gopkg.in/elazarl/goproxy.v1
```

And getting no error message.

I'm closing the issue for the time being, please reopen it if needed.
