### ISSUE TITLE
Tiny error in error return in example httpdump.go

### ISSUE THREAD

**Issue by pschlump** [elazarl/goproxy#81]
In httpdump.go example around line 190 you have

func (t *TeeReadCloser) Close() error {
	err1 := t.c.Close()
	err2 := t.w.Close()
	if err1 == nil && err2 == nil {
		return nil
	}
	if err1 != nil {
		return err2 /// This always return NIL
	}
	return err1
}

This should be:

func (t *TeeReadCloser) Close() error {
	err1 := t.c.Close()
	err2 := t.w.Close()
	if err1 == nil && err2 == nil {
		return nil
	}
	if err1 != nil {
		return err1 // Changed err2 to err1
	}
	return err2 // Changed err1 to err2
}

OR:

func (t *TeeReadCloser) Close() error {
	err1 := t.c.Close()
	err2 := t.w.Close()
	if err1 == nil && err2 == nil {
		return nil
	}
	if err1 == nil {  // Changed != to ==
		return err2 
	}
	return err1
}

**Comment by elazarl** [comment]
Thanks.

Can you send a pull request to fix that?

**Comment by pschlump** [comment]
I can send a pull request.  It will be a few days.
I would like to have a test to validate this - but the test is much more
complicated than the fix and I have to get a better understanding of the
code.

I am also getting this error and looking for the cause.  This happens after
it has been idle for a long period.

goroutine 906 [IO wait, 31 minutes]:
net.runtime_pollWait(0x5b1750, 0x72, 0x0)
/private/var/folders/00/0sdwh000h01000cxqpysvccm0035qk/T/makerelease003761064/go/src/pkg/runtime/netpoll.goc:146
+0x66
net.(*pollDesc).Wait(0xc208298b50, 0x72, 0x0, 0x0)
/usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc208298b50, 0x0, 0x0)
/usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).Read(0xc208298af0, 0xc2083dd000, 0x1000, 0x1000, 0x0,
0x5a93c8, 0x23)
/usr/local/go/src/pkg/net/fd_unix.go:242 +0x34c
net.(*conn).Read(0xc20802e950, 0xc2083dd000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
/usr/local/go/src/pkg/net/net.go:122 +0xe7
bufio.(*Reader).fill(0xc2083ef200)
/usr/local/go/src/pkg/bufio/bufio.go:97 +0x1b3
bufio.(*Reader).Peek(0xc2083ef200, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
/usr/local/go/src/pkg/bufio/bufio.go:132 +0x101
_/Users/corwin/Projects/go-lib/goproxy/transport.(*persistConn).readLoop(0xc20822de00)
/Users/corwin/Projects/go-lib/goproxy/transport/transport.go:553 +0xb6
created by
_/Users/corwin/Projects/go-lib/goproxy/transport.(*Transport).getConn
/Users/corwin/Projects/go-lib/goproxy/transport/transport.go:411 +0x614

It may be Mac specific.  I will test that.



On Mon, Jan 19, 2015 at 1:41 AM, Elazar Leibovich <notifications@github.com>
wrote:

> Thanks.
>
> Can you send a pull request to fix that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elazarl/goproxy/issues/81#issuecomment-70460742>.
>



-- 
Philip Schlump

**Comment by elazarl** [comment]
Thanks. I'll appreciate your tests and pull requests. If you need any explanations of the source code - don't hesttate to ask me.
