### ISSUE TITLE
Ability to build proxy chain

### ISSUE THREAD

**Issue by colorsocean** [elazarl/goproxy#83]
Is there any possibility to build proxy chain?

**Comment by elazarl** [comment]
Hi,

If by proxy chain you mean, have goproxy use other proxy, the answer is
yes.

Set up the transport of the proxy to use other proxy (proxy.Tr).

**Comment by zz** [comment]
Can I use tls or ssl for auth in proxy chain?

**Comment by elazarl** [comment]
Hmmm... I don't think Go have a support for that by default.

But you can write your own RoundTripper, that would use https to connect to
your proxy.

Have a look at SPDY proxy: https://github.com/amahi/spdy-proxy it should be
standard, and allow TLS connection to proxy.

**Comment by elazarl** [comment]
It looks like the issue is resolved, please do not hesitate to reopen if anything is still unclear.
