### ISSUE TITLE
how to HTTP through CONNECT

### ISSUE THREAD

**Issue by zz** [elazarl/goproxy#89]
I want to do HTTP through CONNECT like HTTPS through CONNECT . how to do?

**Comment by elazarl** [comment]
Hi,

If you just want CONNECT HTTP to work (i.e., curl -x localhost:8080 -p
example.com),it should work. See

https://github.com/elazarl/goproxy/issues/43

If you want to eavesdrop to CONNECT HTTP request have a look here:

https://github.com/elazarl/goproxy/issues/55

Does that answer the question?

Thanks,

**Comment by zz** [comment]
for example.  I want 
http_proxy=localhost:8080 curl -I http://www.youtube.com
work with CONNECT HTTP. don't need add -p to curl.

**Comment by elazarl** [comment]
If you wouldn't add -p to curl, it won't use CONNECT, it would just issue
the request to the proxy.

Or am I misunderstanding you?

**Comment by elazarl** [comment]
@zz Is the issue resolved? Can I close it?

**Comment by zz** [comment]
@elazarl yes, please close.
