### ISSUE TITLE
Upstream setup

### ISSUE THREAD

**Issue by bithavoc** [elazarl/goproxy#93]
Hi,

I'd like to use goproxy to proxy connections in a subpath of my web app to a remote upstream server, I'll be adding and changing headers and parameters of the query string in the process.

Would you point to me an example where I can see something like this in action? Or at least tell me how to set it up this way.

Thanks.

**Comment by elazarl** [comment]
Hi,

I'm not sure I understand.

What should the server do when it gets a proxy request?

What should it do when it get a job proxy request?

**Comment by bithavoc** [comment]
Hi,

It should perform the same request to a destination server, I've managed to make it by replaceting the URL property of the `http.Request`, is this the right way to do it?

I'm not sure what a "job proxy request" is.

**Comment by elazarl** [comment]
A non-proxy request. A regular HTTP request directly to the server. Sorry,
sent from the mobile...

**Comment by elazarl** [comment]
@bithavoc Hi,

Are your problems resolved now?

Is there any way to improve documentation so that you wouldn't need to create this issue in the first place?

**Comment by bithavoc** [comment]
I found out that what I needed was to rewrite the Request-URI before delegating it to the proxy library, that did the trick.
