### ISSUE TITLE
Merge upstream transport.go

### ISSUE THREAD

**Issue by anproxx** [elazarl/goproxy#94]
First of all: thank you for such a nice piece of software!

As I found out, the file transport/transport.go was copied from the original golang sources and adjusted to fit your needs. Since that time several bug fixes and improvements have been applied in the original golang sources, that have not been merged into your version of transport.go. Some of these bugfixes are quite important for me. 

Could you merge the upstream changes into goproxy? I already tried this, but as our initial version of transport.go in this repo already contains your changes, it is not so easy for me to find out what you have changed actually.

**Comment by elazarl** [comment]
Hi,

goproxy doesn't use transport.go anymore. I left it just so that I wouldn't break backwards compatibility.

**Comment by anproxx** [comment]
Ok, the goproxy-httpdump example is the only reference to it anymore. Did not notice that. Looks like I should update my go interpreter to get the upstream bugfixes for transport ;-).

Thank you.

**Comment by j16sdiz** [comment]
@elazarl May you add a comment on `transport.go` ?
I just spend 30+ minutes on that file and found it not used =(

**Comment by elazarl** [comment]
Good idea. I left it for backwards compatibility.

Do you want to send a PR?
