### ISSUE TITLE
Create dialer depending on fields in request header

### ISSUE THREAD

**Issue by anproxx** [elazarl/goproxy#95]
Hi,

I'm trying to create a dialer to connect to the backend, that behaves different depending of information found in the Request. Do you see a way how to achieve this?

The problem is that when I overwrite `proxy.Tr.Dial`, I only get `network` and `addr string` as parameters and have no reference to `http.Request`. I tried to overwrite `ctx.proxy.Tr.Dial` from a `proxy.OnRequest().DoFunc(func(r *http.Request,ctx *goproxy.ProxyCtx)(*http.Request,*http.Response){ ... })`, but as `proxy` in `ctx.proxy` is lowercase, it is protected and cannot be accessed from outside (even if it would be possible, I think `ctx.proxy` is a reference to the global `proxy` instance, so that on concurrent requests the requests would overwrite the Dialer of each other).

Thank you!

**Comment by anproxx** [comment]
Solved the issue by setting a custom ctx.RoundTripper in OnRequest().DoFunc which creates a new http.Transport with a custom Dailer for each connection.

**Comment by elazarl** [comment]
Exactly! That's the solution I intended.
Sorry for not replying earlier.
